/**
 * Content Planner — The intelligence layer between extraction and generation.
 * Takes raw CourseIR and produces a structured CoursePlan that:
 *   1. Cleans noise (junk variables, decorative shapes, auto-generated names)
 *   2. Understands course structure and narrative flow
 *   3. Groups slides into logical sections
 *   4. Classifies content for optimal deep-scroll presentation
 *   5. Preserves all meaningful interactions, triggers, and states
 *   6. Produces a verification report of what was kept vs dropped
 *
 * Output: CoursePlan { meta, sections[], quizBanks[], verification }
 */
window.ContentPlanner = (function () {
  'use strict';

  // ---- Noise detection ----

  // ---- Structural junk detection ----
  // These detect text that is structurally an authoring tool artefact,
  // not course content. Based on characteristics, not specific phrases.

  /**
   * Detect text that is an auto-generated label from Articulate Storyline.
   *
   * Storyline universally generates names for objects, layers, and slides using
   * these patterns:
   * - Shape names: "Rectangle 1", "Oval 3", "Freeform 2", "Rounded Rectangle 5"
   * - Structure labels: "Group 1", "Layer 2", "Slide 3.1", "Scene 2"
   * - Quiz type labels used as slide titles: "Pick One", "Pick Many", "True/False",
   *   "Text Entry", "Matching", "Sequence", "Fill In"
   * - Object references: 11-char alphanumeric hashes ("5oTbjsyGwCV") — these
   *   sometimes appear as text content when alt-text or labels are auto-filled
   *
   * Detection: short text matching "generic_noun" + optional whitespace + optional number,
   * OR Storyline's quiz type naming pattern, OR an object hash reference.
   */
  function isAutogeneratedLabel(text) {
    if (!text) return true;
    var t = text.trim();
    if (t.length < 2) return true;

    // Storyline object hash: 11-char alphanumeric (e.g., "5oTbjsyGwCV")
    if (/^[A-Za-z0-9]{10,22}$/.test(t)) return true;

    // Storyline quiz type labels used as slide titles
    var quizTypeLabels = [
      'pick one', 'pick many', 'pick all', 'true/false', 'true false',
      'text entry', 'matching', 'sequence', 'fill in', 'fill in the blank',
      'drag and drop', 'freeform', 'graded question', 'survey question',
      'multiple choice', 'word bank', 'hotspot'
    ];
    if (quizTypeLabels.indexOf(t.toLowerCase()) !== -1) return true;

    // Generic noun + optional number pattern
    if (/^[a-zA-Z\s]{2,25}\s*\d*$/i.test(t)) {
      var word = t.replace(/\s*\d+$/, '').trim().toLowerCase();
      var genericTerms = [
        'rectangle', 'oval', 'shape', 'freeform', 'group', 'layer',
        'slide', 'scene', 'text', 'button', 'image', 'picture', 'photo',
        'round diagonal corner', 'rounded rectangle', 'caption',
        'textbox', 'placeholder', 'frame', 'panel', 'box', 'object',
        'item', 'element', 'block', 'region', 'zone', 'area', 'hotspot',
        'marker', 'dial', 'slider', 'scrolling panel', 'trigger',
        'pentagon', 'hexagon', 'triangle', 'circle', 'star', 'diamond',
        'trapezoid', 'parallelogram', 'cross', 'arrow', 'chevron'
      ];
      if (genericTerms.indexOf(word) !== -1) return true;
    }

    // Scene/slide numbering: "Slide 2.1", "Scene 3"
    if (/^(slide|scene)\s*\d+(\.\d+)?$/i.test(t)) return true;

    // Bare number used as slide title: "0", "1", "2" etc.
    if (/^\d+$/.test(t)) return true;

    // "Table N" or "Table 01 Drag and Drop - X" — Storyline internal naming for
    // drag-and-drop and table-based slides
    if (/^table\s+\d/i.test(t)) return true;

    // ALL CAPS internal names like "TABLE SUMMARY", "GHOST / LABELS"
    if (/^[A-Z\s\/\-]{4,}$/.test(t) && t === t.toUpperCase() && t.length < 30) return true;

    return false;
  }

  /**
   * Detect icon/shape alt-text that Storyline auto-generates.
   *
   * Storyline universally generates alt-text for decorative shapes/icons using
   * the pattern: "[descriptive word] icon [number]" or "[descriptive word] [number]"
   * Examples: "arrow icon 1", "electricity icon 1", "CHECK icon 1", "lock icon 1",
   *           "Line 1", "Line 2", "magnifying glass icon 1", "Tick icon 1"
   *
   * Also catches connector/line labels: "Line N" pattern.
   * And repeated tick/check/cross icons used for table formatting.
   */
  function isIconOrShapeAltText(text) {
    if (!text) return false;
    var t = text.trim();

    // "word(s) icon N" pattern — universal Storyline icon alt-text
    if (/^[\w\s-]+icon\s*\d*$/i.test(t)) return true;

    // "Line N" — connector/line shape labels
    if (/^line\s*\d+$/i.test(t)) return true;

    // "Arrow N" — navigation arrow shapes
    if (/^arrow\s*\d+$/i.test(t)) return true;

    // Repeated tick/check/cross markers used in tables
    if (/^(tick|check|cross|x)\s*(icon)?\s*\d*$/i.test(t)) return true;

    // Table accessibility descriptions: "Table with N columns and N rows"
    if (/^table\s+with\s+\d+\s+columns?\s+and\s+\d+\s+rows?$/i.test(t)) return true;

    // "Left/Right/Up/Down Arrow N" — directional shape labels
    if (/^(left|right|up|down)\s+arrow\s*\d*$/i.test(t)) return true;

    return false;
  }

  /**
   * Detect developer/author notes left in courses.
   *
   * Authors sometimes leave notes like "DEVELOPER NOTE:", "TODO:", "NOTE:",
   * "PLACEHOLDER" in their courses. These are never intended for learners.
   */
  function isDeveloperNote(text) {
    if (!text) return false;
    var t = text.trim();
    return /^(DEVELOPER\s*NOTE|TODO|NOTE\s*TO\s*SELF|PLACEHOLDER|TBD|WIP)\s*[:\-]/i.test(t) ||
           /TO\s*BE\s*ADDED/i.test(t) ||
           /REMOVE\s*BEFORE\s*PUBLISH/i.test(t);
  }

  /**
   * Detect text that is purely a conditional visibility label.
   *
   * Storyline authors add text like "technical only", "admin only", "manager view"
   * as labels for conditional content. These are authoring annotations, not content.
   * Pattern: 1-3 short words ending with "only" or starting with "if".
   */
  function isConditionalLabel(text) {
    if (!text) return false;
    var t = text.trim().toLowerCase();
    if (t.length > 30) return false;
    return /^\w+(\s+\w+)?\s+only$/i.test(t) ||
           /^(show|hide)\s+(if|when|for)/i.test(t);
  }

  /**
   * Detect text that is a single-word UI label or quiz keyword.
   * These are structural labels, not teaching content.
   * Characteristics: very short, single word or two, matches common UI vocabulary.
   */
  function isSingleWordUILabel(text) {
    var t = (text || '').trim().toLowerCase();
    if (t.length > 30) return false; // Only short text can be a label
    // Single-word or very short labels that are structural
    var uiLabels = [
      'question', 'correct', 'incorrect', 'submit', 'prev', 'next',
      'back', 'continue', 'true', 'false', 'results', 'result',
      'introduction', 'conclusion', 'summary', 'review',
      'pick one', 'pick many', 'pick all', 'multiple choice',
      'knowledge check', 'check', 'quiz', 'test', 'assessment',
      'drag and drop', 'matching', 'sequence', 'fill in',
      'click here', 'tap here', 'select', 'choose'
    ];
    return uiLabels.indexOf(t) !== -1;
  }

  /**
   * Detect text that contains only variable references or score placeholders.
   * Authoring tools embed runtime variables like %_player.Score% that render
   * as literal strings when not in the original player.
   */
  function isVariableOnlyText(text) {
    if (!text) return true;
    // Strip all variable patterns: %_player.xxx%, %variable%, $variable
    var stripped = text
      .replace(/%_player\.[^%]+%/g, '')
      .replace(/%[^%]+%/g, '')
      .replace(/\$\w+/g, '')
      .replace(/[\s\^\.,:;!?]+/g, '')
      .trim();
    return stripped.length < 3;
  }

  /**
   * Detect player navigation / interaction instruction text.
   * These are instructions about HOW to interact with the e-learning player,
   * not WHAT the learner should learn.
   *
   * Detection strategy based on characteristics:
   * - Short text (under ~100 chars) — real teaching content tends to be longer
   * - Contains an interaction verb (click, tap, drag, hover, select, press, swipe, scroll)
   * - The verb targets a UI element (arrow, button, tab, icon, menu, item, option)
   *   OR describes a navigation action (continue, proceed, begin, explore, navigate)
   *
   * This catches any authoring tool's instruction text, not just Storyline's.
   */
  function isPlayerInstructionText(text) {
    if (!text) return false;
    var t = text.trim();

    // Only short text can be purely instructional.
    // Longer text likely has teaching content mixed with an instruction.
    if (t.length > 100) return false;

    var lower = t.toLowerCase();

    // Interaction verbs — the actions a user takes with a player UI
    var interactionVerbs = ['click', 'tap', 'drag', 'hover', 'swipe', 'scroll',
      'press', 'roll over', 'mouse over', 'touch'];
    var hasInteractionVerb = interactionVerbs.some(function (v) { return lower.includes(v); });

    // Navigation/exploration verbs
    var navVerbs = ['navigate', 'explore', 'use the', 'select the', 'choose the',
      'make your', 'pick the', 'find the', 'rotate the', 'move the'];
    var hasNavVerb = navVerbs.some(function (v) { return lower.includes(v); });

    if (!hasInteractionVerb && !hasNavVerb) return false;

    // UI element targets — things you interact with in a player, not course content
    var uiTargets = ['arrow', 'button', 'tab', 'icon', 'menu', 'item', 'option',
      'slider', 'scrollbar', 'scroll bar', 'hotspot', 'tile', 'card',
      'panel', 'section', 'link', 'image', 'thumbnail', 'marker', 'submit'];
    var hasUITarget = uiTargets.some(function (t) { return lower.includes(t); });

    // Navigation action targets
    var navTargets = ['continue', 'proceed', 'begin', 'start', 'advance',
      'move on', 'go to', 'next', 'forward', 'learn more',
      'explore', 'discover', 'view', 'see more', 'read more',
      'reveal', 'show', 'access', 'open', 'launch'];
    var hasNavTarget = navTargets.some(function (t) { return lower.includes(t); });

    // Instruction starters — text that begins with telling the user what to do
    var instructionStarters = ['click on', 'tap on', 'drag the', 'drag each',
      'hover over', 'use the', 'select the', 'choose the', 'press the',
      'scroll down', 'scroll up', 'swipe', 'navigate', 'make your selection',
      'make your choice', 'move the image'];
    var startsWithInstruction = instructionStarters.some(function (s) { return lower.startsWith(s); });

    // "clicking and dragging" — physical interaction instruction
    if (lower.indexOf('clicking and dragging') !== -1) return true;

    // "hit submit" / "and then hit" — Storyline submit instruction
    if (/\bhit\s+submit\b/i.test(lower) || /\band\s+then\s+hit\b/i.test(lower)) return true;

    // Very short interaction commands: "Click to reveal", "Tap to continue"
    // Pattern: verb + "to" + action (under 30 chars)
    var isShortCommand = t.length < 30 && /^(click|tap|press|touch)\s+to\s+/i.test(t);

    // "Hover over" is always a player instruction
    if (/^hover\s+over/i.test(lower)) return true;

    // It's a player instruction if it has an interaction verb + UI target,
    // or starts with an instruction phrase, or has nav verb + nav target,
    // or is a short "verb to action" command
    return (hasInteractionVerb && hasUITarget) ||
           (hasInteractionVerb && hasNavTarget) ||
           (hasNavVerb && hasUITarget) ||
           (hasNavVerb && hasNavTarget) ||
           startsWithInstruction ||
           isShortCommand;
  }

  /**
   * Master junk text detection — combines all checks.
   */
  function isJunkText(text) {
    if (!text || text.trim().length < 2) return true;
    if (isAutogeneratedLabel(text)) return true;
    if (isSingleWordUILabel(text)) return true;
    if (isVariableOnlyText(text)) return true;
    if (isIconOrShapeAltText(text)) return true;
    if (isDeveloperNote(text)) return true;
    if (isConditionalLabel(text)) return true;
    return false;
  }

  /**
   * Detect text that is not junk but is also not meaningful course content.
   * This is the "noise" layer — player instructions that look like sentences
   * but don't teach anything.
   */
  function isStorylineUIText(text) {
    if (!text) return false;
    return isPlayerInstructionText(text);
  }

  function isNavigationElement(el) {
    if (el.type !== 'button') return false;
    var label = (el.label || '').toLowerCase();
    return label === '<' || label === '>' || label === 'prev' ||
      label === 'next' || label === 'back' || label === 'continue' ||
      label === 'submit' || label.includes('hotspot') ||
      label.length <= 1;
  }

  function isMeaningfulText(text) {
    if (!text || isJunkText(text)) return false;
    if (isStorylineUIText(text)) return false;
    var cleaned = text.replace(/\s+/g, ' ').trim();
    if (cleaned.length <= 3) return false;

    // Detect text that is just repeated icon/shape alt-text concatenated together.
    // Storyline tables and grids often produce text like
    // "Tick icon 1 Tick icon 1 Tick icon 1..." when cells contain identical icons.
    // Check if the text is mostly repetitions of short icon-like fragments.
    if (cleaned.length > 20) {
      var iconPattern = /\b[\w\s-]+icon\s*\d+\b/gi;
      var iconMatches = cleaned.match(iconPattern);
      if (iconMatches) {
        var iconTextLength = iconMatches.join('').length;
        // If >60% of the text is icon references, it's decorative
        if (iconTextLength / cleaned.length > 0.6) return false;
      }
    }

    return true;
  }

  // ---- Section grouping ----

  /**
   * Detect slides that serve as course MENU/NAVIGATION rather than content.
   *
   * Storyline courses often have a "menu" or "table of contents" slide that
   * links to different sections. These should inform STRUCTURE but not be
   * rendered as content sections.
   *
   * Universal detection:
   * - Slide title contains "menu" or "table of contents" or "contents"
   * - Slide has many navigation triggers (gotoplay actions)
   * - Slide is mostly buttons/links with short labels
   */
  function isMenuSlide(slide) {
    var title = (slide.title || '').trim().toLowerCase();
    if (/^(menu|table\s*of\s*contents|contents|navigation|nav)\s*\d*$/i.test(title)) return true;
    return false;
  }

  /**
   * Detect slides that are glossary/reference and should be presented differently.
   */
  function isGlossarySlide(slide) {
    var title = (slide.title || '').trim().toLowerCase();
    return /^glossary/i.test(title);
  }

  /**
   * Group slides into logical sections based on course structure.
   * Storyline courses typically have: title > content > quiz > results
   * We detect natural section breaks (title slides, topic changes, quiz boundaries).
   *
   * Key grouping rules:
   * - Menu/navigation slides are excluded from content
   * - Consecutive quiz slides are grouped into a single assessment section
   * - Consecutive results slides are grouped into a single results section
   */
  function groupIntoSections(slides) {
    // Pre-filter: remove menu/nav slides (they inform structure, not content)
    var contentSlides = slides.filter(function (s) {
      return !isMenuSlide(s);
    });

    var sections = [];
    var currentSection = null;

    var lastSceneId = null;

    for (var i = 0; i < contentSlides.length; i++) {
      var slide = contentSlides[i];
      var shouldBreak = false;

      // Scene boundary: Storyline scenes are the author's logical grouping.
      // A new scene always starts a new section (unless it's a results/quiz continuation).
      var sceneChanged = slide.sceneId && slide.sceneId !== lastSceneId;
      lastSceneId = slide.sceneId || lastSceneId;

      // Start a new section on:
      if (slide.type === 'title') shouldBreak = true;
      else if (slide.type === 'results') {
        // Group consecutive results slides together
        if (!currentSection || currentSection.type !== 'results') shouldBreak = true;
      }
      else if (slide.type === 'branching') shouldBreak = true;
      else if (slide.type === 'form') shouldBreak = true;
      else if (slide.type === 'quiz') {
        // Group consecutive quiz slides into one assessment section
        if (!currentSection || currentSection.type !== 'assessment') shouldBreak = true;
      }
      else if (sceneChanged) shouldBreak = true;
      else if (!currentSection) shouldBreak = true;

      // Also break when the slide type significantly differs from the current section
      // (e.g., objectives after a title, content after form)
      if (currentSection && !shouldBreak) {
        var prevType = currentSection.slides[currentSection.slides.length - 1].type;
        if (prevType === 'title' && slide.type !== 'title') shouldBreak = true;
        // Break out of assessment when hitting non-quiz content
        if (currentSection.type === 'assessment' && slide.type !== 'quiz') shouldBreak = true;
        // Break out of results when hitting non-results content
        if (currentSection.type === 'results' && slide.type !== 'results') shouldBreak = true;
      }

      // Also break if there's a big topic shift (title keywords change significantly)
      if (currentSection && currentSection.slides.length >= 5 && slide.type === 'content') {
        var prevSlide = currentSection.slides[currentSection.slides.length - 1];
        if (prevSlide && isTopicShift(prevSlide.title, slide.title)) {
          shouldBreak = true;
        }
      }

      if (shouldBreak) {
        currentSection = {
          id: 'section_' + sections.length,
          type: classifySectionType(slide),
          title: deriveSectionTitle(slide, sections.length),
          slides: []
        };
        sections.push(currentSection);
      }

      currentSection.slides.push(planSlide(slide));
    }

    // Post-process: consolidate slides with similar titles (common prefix 10+ chars)
    sections.forEach(function (section) {
      if (section.slides.length < 2) return;
      var consolidated = [];
      var i = 0;
      while (i < section.slides.length) {
        var current = section.slides[i];
        var currentTitle = (current.originalTitle || '').trim();
        // Find consecutive slides with a shared prefix of 10+ chars
        var group = [current];
        var j = i + 1;
        while (j < section.slides.length && currentTitle.length >= 10) {
          var nextTitle = (section.slides[j].originalTitle || '').trim();
          var prefixLen = 0;
          var maxCheck = Math.min(currentTitle.length, nextTitle.length);
          while (prefixLen < maxCheck && currentTitle.charAt(prefixLen) === nextTitle.charAt(prefixLen)) {
            prefixLen++;
          }
          if (prefixLen >= 10) {
            group.push(section.slides[j]);
            j++;
          } else {
            break;
          }
        }
        if (group.length > 1) {
          // Merge group into a single slide: combine all body texts, headings, layers
          var merged = group[0];
          for (var k = 1; k < group.length; k++) {
            var donor = group[k];
            if (donor.content) {
              if (donor.content.bodyTexts) {
                merged.content.bodyTexts = merged.content.bodyTexts.concat(donor.content.bodyTexts);
              }
              if (donor.content.headings) {
                donor.content.headings.forEach(function (h) {
                  // Only add heading if not duplicated
                  var exists = merged.content.headings.some(function (mh) {
                    return mh.text.toLowerCase() === h.text.toLowerCase();
                  });
                  if (!exists) merged.content.headings.push(h);
                });
              }
              if (donor.content.images) {
                merged.content.images = merged.content.images.concat(donor.content.images);
              }
              if (donor.content.callouts) {
                merged.content.callouts = merged.content.callouts.concat(donor.content.callouts);
              }
            }
            if (donor.layers && donor.layers.length > 0) {
              merged.layers = (merged.layers || []).concat(donor.layers);
            }
            // Preserve interactions from merged slides
            if (donor.interactions && donor.interactions.length > 0) {
              merged.interactions = (merged.interactions || []).concat(donor.interactions);
            }
            // Preserve videos and audio from merged slides
            if (donor.content.videos && donor.content.videos.length > 0) {
              merged.content.videos = (merged.content.videos || []).concat(donor.content.videos);
            }
            if (donor.content.audio && donor.content.audio.length > 0) {
              merged.content.audio = (merged.content.audio || []).concat(donor.content.audio);
            }
          }
          consolidated.push(merged);
        } else {
          consolidated.push(current);
        }
        i = j;
      }
      section.slides = consolidated;
    });

    // Post-process 1: Improve generic section titles using content headings.
    // When a section title is a generic fallback (Choose Your Path, Section N intro,
    // Introduction), scan the section's slides for the first meaningful heading
    // and use that as the section title instead.
    var genericTitles = ['choose your path', 'introduction', 'section'];
    sections.forEach(function (s) {
      var lower = s.title.toLowerCase();
      var isGeneric = genericTitles.some(function (g) { return lower.indexOf(g) === 0; }) ||
                      /^section\s*\d+\s*(intro|introduction)?$/i.test(s.title) ||
                      /^intro$/i.test(s.title);
      if (!isGeneric) return;

      // Scan slides for first meaningful heading
      for (var si = 0; si < s.slides.length; si++) {
        var slide = s.slides[si];
        if (slide.content && slide.content.headings) {
          for (var hi = 0; hi < slide.content.headings.length; hi++) {
            var heading = slide.content.headings[hi].text;
            if (heading && heading.length > 3 && heading.length < 60 &&
                !isAutogeneratedLabel(heading) && !isIconOrShapeAltText(heading)) {
              s.title = cleanSectionTitle(heading);
              return; // Found a good title, stop searching
            }
          }
        }
        // Also try the slide title if it's meaningful
        var slideTitle = (slide.originalTitle || '').trim();
        if (slideTitle && slideTitle.length > 3 && slideTitle.length < 60 &&
            !isAutogeneratedLabel(slideTitle) &&
            !/^section\s*\d/i.test(slideTitle) &&
            !/^intro$/i.test(slideTitle)) {
          s.title = cleanSectionTitle(slideTitle);
          return;
        }
      }
    });

    // Post-process 2: deduplicate section titles
    var titleCounts = {};
    sections.forEach(function (s) {
      var key = s.title.toLowerCase();
      titleCounts[key] = (titleCounts[key] || 0) + 1;
    });
    var titleSeen = {};
    sections.forEach(function (s) {
      var key = s.title.toLowerCase();
      if (titleCounts[key] > 1) {
        titleSeen[key] = (titleSeen[key] || 0) + 1;
        if (titleSeen[key] > 1) {
          s.title = s.title + ' (Part ' + titleSeen[key] + ')';
        }
      }
    });

    return sections;
  }

  function isTopicShift(prevTitle, nextTitle) {
    if (!prevTitle || !nextTitle) return false;
    var prevWords = new Set(prevTitle.toLowerCase().split(/\s+/).filter(function (w) { return w.length > 3; }));
    var nextWords = new Set(nextTitle.toLowerCase().split(/\s+/).filter(function (w) { return w.length > 3; }));
    if (prevWords.size === 0 || nextWords.size === 0) return false;
    var overlap = 0;
    prevWords.forEach(function (w) { if (nextWords.has(w)) overlap++; });
    return overlap === 0;
  }

  function classifySectionType(firstSlide) {
    if (firstSlide.type === 'title') return 'hero';
    if (firstSlide.type === 'results') return 'results';
    if (firstSlide.type === 'branching') return 'branching';
    if (firstSlide.type === 'quiz') return 'assessment';
    if (firstSlide.type === 'form') return 'form';
    return 'content';
  }

  /**
   * Clean a section title for display.
   * Converts ALL CAPS internal names to title case,
   * strips trailing whitespace.
   */
  function cleanSectionTitle(title) {
    if (!title) return title;
    var t = title.trim();
    // ALL CAPS internal names like "GHOST / LABELS", "TABLE SUMMARY"
    if (/^[A-Z\s\/\-&]+$/.test(t) && t.length < 30) {
      t = t.toLowerCase().replace(/\b\w/g, function(c) { return c.toUpperCase(); });
    }
    return t;
  }

  function deriveSectionTitle(slide, sectionIndex) {
    if (slide.type === 'title') return cleanSectionTitle(slide.title) || 'Welcome';
    if (slide.type === 'results') return 'Your Results';
    if (slide.type === 'branching') {
      var branchTitle = (slide.title || '').trim();
      if (!branchTitle || isAutogeneratedLabel(branchTitle)) return 'Choose Your Path';
      return cleanSectionTitle(branchTitle);
    }

    // Quiz/assessment sections: Storyline uses internal names like "Section 3 Q1",
    // "Pick One", "Drag and Drop 1". Use a meaningful default instead.
    if (slide.type === 'quiz') {
      var quizTitle = (slide.title || '').trim();
      if (!quizTitle || isAutogeneratedLabel(quizTitle) ||
          /^section\s*\d+\s*(q\d+|quiz|intro)?$/i.test(quizTitle) ||
          /^(drag\s*(and|&)\s*drop|match\s*the)\s*\d*$/i.test(quizTitle)) {
        return 'Knowledge Check';
      }
      return cleanSectionTitle(quizTitle);
    }

    // Form/quiz slides often have Storyline's auto-generated type labels as titles
    if (slide.type === 'form') {
      var title = (slide.title || '').trim();
      if (!title || isAutogeneratedLabel(title)) {
        return 'Your Details';
      }
      return cleanSectionTitle(title);
    }

    // For all other slide types, check if title is meaningful
    var anyTitle = (slide.title || '').trim();
    if (!anyTitle || isAutogeneratedLabel(anyTitle)) {
      if (sectionIndex === 0) return 'Introduction';
      return 'Section ' + (sectionIndex + 1);
    }
    return cleanSectionTitle(anyTitle);
  }

  // ---- Slide planning ----

  /**
   * Plan how a single slide should be presented in the deep-scroll output.
   * Extracts all meaningful content and classifies presentation style.
   */
  function planSlide(slide) {
    var plan = {
      id: slide.id,
      originalTitle: slide.title,
      type: slide.type,
      slideNumber: slide.slideNumber,
      locked: slide.locked || false,
      hasNavRestriction: slide.hasNavRestriction || false,
      presentation: 'standard',
      content: {
        headings: [],
        bodyTexts: [],
        callouts: [],
        images: [],
        videos: [],
        audio: []
      },
      layers: [],
      interactions: [],
      triggers: [],
      states: [],
      formFields: [],
      quizData: null
    };

    // Extract and classify all meaningful text
    slide.elements.forEach(function (el) {
      if (el.type === 'text' && isMeaningfulText(el.content)) {
        var cleaned = cleanTextContent(el.content);
        if (el.role === 'heading') {
          plan.content.headings.push({
            text: cleaned,
            fontSize: el.fontSize,
            fontFamily: el.fontFamily,
            color: el.color,
            align: el.textAlign
          });
        } else if (el.role === 'callout') {
          plan.content.callouts.push(cleaned);
        } else {
          plan.content.bodyTexts.push(cleaned);
        }
      }

      if (el.type === 'image' && el.assetId !== -1) {
        var imgRole = el.instructionalRole || 'content';

        // Skip decorative and icon images — they're UI chrome, not course content.
        // These are universal Storyline artefacts: gradient overlays, shape fills,
        // navigation markers, and tiny decorative elements.
        if (imgRole === 'decorative' || imgRole === 'icon') {
          // Skip — don't include in output
        } else {
          plan.content.images.push({
            assetId: el.assetId,
            originalPath: el.originalPath,
            altText: el.altText,
            role: imgRole,
            width: el.width,
            height: el.height,
            originalWidth: el.originalWidth,
            originalHeight: el.originalHeight
          });
        }
      }

      if (el.type === 'video') {
        plan.content.videos.push({
          assetId: el.assetId,
          originalPath: el.originalPath,
          durationMs: el.durationMs,
          posterPath: el.posterPath,
          posterAssetId: el.posterAssetId
        });
      }

      if (el.type === 'audio') {
        plan.content.audio.push({
          assetId: el.assetId,
          originalPath: el.originalPath,
          durationMs: el.durationMs
        });
      }

      // Capture interactions (hotspots, sliders, scroll panels)
      if (el.type === 'interaction') {
        plan.interactions.push({
          type: el.interactionType,
          label: el.label,
          variableName: el.variableName,
          children: (el.children || []).map(function (c) {
            return { type: c.type, content: c.content || c.label, role: c.role };
          })
        });
      }

      // Capture meaningful buttons (for branching options and states)
      // Filter out buttons whose labels are icon alt-text or auto-generated names
      if (el.type === 'button' && !isNavigationElement(el) &&
          !isIconOrShapeAltText(el.label) && !isJunkText(el.label)) {
        if (!plan.buttons) plan.buttons = [];
        plan.buttons.push({
          id: el.id,
          label: cleanButtonLabel(el.label),
          action: el.action
        });
        if (el.states && el.states.length > 0) {
          plan.states.push({
            elementId: el.id,
            label: el.label,
            states: el.states.map(function (s) {
              return { name: s.name, label: s.label, altText: s.altText };
            })
          });
        }
      }

      // Capture form fields
      if (el.type === 'form' && el.fields) {
        plan.formFields = el.fields.map(function (f) {
          return {
            label: f.label,
            fieldType: f.fieldType,
            variableName: f.variableName,
            required: f.required
          };
        });
      }

      // Capture quiz data
      if (el.type === 'quiz' && el.question) {
        plan.quizData = el.question;
      }
    });

    // Also check audioNarrationId
    if (slide.audioNarrationId) {
      plan.content.audio.push({
        assetId: slide.audioNarrationId,
        originalPath: '',
        durationMs: 0,
        isNarration: true
      });
    }

    // Plan layers with full content preservation
    if (slide.layers && slide.layers.length > 0) {
      plan.layers = slide.layers
        .filter(function (l) { return l.elements && l.elements.length > 0; })
        .filter(function (l) { return !isDragDropFeedbackLayer(l); })
        .map(function (layer) { return planLayer(layer); })
        .filter(function (l) { return l.hasContent; });
    }

    // Capture slide-level triggers
    if (slide.triggers && slide.triggers.length > 0) {
      plan.triggers = slide.triggers.map(function (t) {
        return {
          id: t.id,
          event: t.event,
          actions: t.actions,
          conditions: t.conditions,
          targetObjectId: t.targetObjectId
        };
      });
    }

    // Deduplicate content: same text appearing in multiple layers/states
    // This is universal — Storyline courses often have the same text in
    // different states (normal, hover, visited) or repeated across layers
    // that show different configurations of the same content.
    plan.content.bodyTexts = deduplicateTexts(plan.content.bodyTexts);
    plan.content.headings = deduplicateHeadings(plan.content.headings);

    // Determine presentation style
    plan.presentation = classifyPresentation(plan);

    return plan;
  }

  /**
   * Remove duplicate text strings, keeping first occurrence.
   * Also removes text that is internally repetitive (same sentences
   * listed forward then reversed — a common Storyline pattern from
   * interactive content states).
   */
  function deduplicateTexts(texts) {
    var seen = {};
    return texts.filter(function (t) {
      var key = t.replace(/\s+/g, ' ').trim().toLowerCase();
      if (seen[key]) return false;
      seen[key] = true;
      return true;
    }).map(function (t) {
      // Remove internal repetition: split into sentences and deduplicate
      return removeInternalRepetition(t);
    });
  }

  /**
   * Remove internally repeated content within a single text block.
   * Storyline interactive content (flip cards, rotating content) often produces
   * text where the same sentences appear multiple times because the parser
   * extracts from multiple states of the same object.
   */
  function removeInternalRepetition(text) {
    if (!text || text.length < 80) return text;

    // Strategy 1: Split on sentence boundaries (periods, !, ?) and deduplicate
    var sentences = text.split(/(?<=[.!?])\s+/).filter(function (s) { return s.trim().length > 10; });
    if (sentences.length >= 4) {
      var seen = {};
      var unique = sentences.filter(function (s) {
        var key = s.trim().toLowerCase();
        if (seen[key]) return false;
        seen[key] = true;
        return true;
      });

      if (unique.length < sentences.length * 0.8) {
        return unique.join(' ');
      }
    }

    // Strategy 2: Sliding window phrase repetition detection.
    // Storyline often concatenates content WITHOUT periods — just space-separated.
    // If the same phrase of 8+ words appears twice, remove the second occurrence.
    // Normalize words: strip special characters (em dashes, etc.) that break matching.
    var words = text.split(/\s+/);
    var normalizedWords = words.map(function (w) {
      return w.toLowerCase().replace(/[^\w]/g, '');
    }).filter(function (w) { return w.length > 0; });

    if (normalizedWords.length >= 16) {
      var windowSize = 6; // Reduced from 8 to catch more patterns
      var phraseSeen = {};
      var cutIndex = -1;
      for (var i = 0; i <= normalizedWords.length - windowSize; i++) {
        var phrase = normalizedWords.slice(i, i + windowSize).join(' ');
        if (phraseSeen[phrase] !== undefined && i - phraseSeen[phrase] >= windowSize) {
          // Map back from normalized index to original word index
          cutIndex = i;
          break;
        }
        if (phraseSeen[phrase] === undefined) {
          phraseSeen[phrase] = i;
        }
      }
      if (cutIndex > 0) {
        // Map normalized index back to original text: take first cutIndex words
        // (approximately, since some normalized words were filtered)
        var origWords = text.split(/\s+/);
        var normalCount = 0;
        var origCut = 0;
        for (var wi = 0; wi < origWords.length; wi++) {
          var nw = origWords[wi].toLowerCase().replace(/[^\w]/g, '');
          if (nw.length > 0) {
            if (normalCount >= cutIndex) { origCut = wi; break; }
            normalCount++;
          }
        }
        if (origCut > 0) {
          return origWords.slice(0, origCut).join(' ');
        }
      }
    }

    return text;
  }

  function deduplicateHeadings(headings) {
    var seen = {};
    return headings.filter(function (h) {
      var key = h.text.replace(/\s+/g, ' ').trim().toLowerCase();
      if (seen[key]) return false;
      seen[key] = true;
      return true;
    });
  }

  /**
   * Detect drag-and-drop feedback layers.
   * Storyline drag-and-drop slides have feedback layers containing confirmation
   * prompts ("Are you happy with your answer?") and result displays ("ICE =",
   * "BEV ="). These are interaction feedback, not learning content.
   */
  function isDragDropFeedbackLayer(layer) {
    if (!layer || !layer.elements) return false;
    var textElements = layer.elements.filter(function (el) {
      return el.type === 'text' && el.content && el.content.trim().length > 0;
    });
    if (textElements.length === 0) return false;

    var allTexts = textElements.map(function (el) { return el.content.trim(); });
    var combined = allTexts.join(' ').toLowerCase();

    // Confirmation prompt pattern
    if (combined.indexOf('are you happy with your answer') !== -1) return true;

    // Check if most texts are short abbreviation = value patterns (e.g. "ICE =", "BEV =")
    var abbrevCount = 0;
    allTexts.forEach(function (t) {
      // Matches "XXX =" or "XXX = something" where XXX is short (1-6 chars)
      if (/^[A-Za-z0-9\/\-]{1,6}\s*=/.test(t.trim())) abbrevCount++;
    });
    // If majority of texts are abbreviation=value patterns, it's feedback
    if (abbrevCount > 0 && abbrevCount >= allTexts.length * 0.5) return true;

    return false;
  }

  /**
   * Plan a layer's content and interaction style.
   */
  function planLayer(layer) {
    var texts = [];
    var images = [];
    var videos = [];
    var audio = layer.audio || [];
    var interactions = [];

    layer.elements.forEach(function (el) {
      if (el.type === 'text' && isMeaningfulText(el.content)) {
        texts.push({
          content: cleanTextContent(el.content),
          role: el.role,
          fontSize: el.fontSize
        });
      }
      if (el.type === 'image' && el.assetId !== -1) {
        images.push({
          assetId: el.assetId,
          originalPath: el.originalPath,
          altText: el.altText,
          role: el.instructionalRole || 'content'
        });
      }
      if (el.type === 'video') {
        videos.push({
          assetId: el.assetId,
          originalPath: el.originalPath,
          durationMs: el.durationMs
        });
      }
      if (el.type === 'interaction') {
        interactions.push({
          type: el.interactionType,
          label: el.label,
          children: el.children || []
        });
      }
    });

    var layerTriggers = (layer.triggers || []).map(function (t) {
      return {
        id: t.id,
        event: t.event,
        actions: t.actions,
        conditions: t.conditions
      };
    });

    // Improve generic layer names using content
    var layerName = layer.name;
    if (/^Layer\s*\d*$/i.test(layerName) && texts.length > 0) {
      // Prefer a unique, descriptive text (long enough to be meaningful, not too long)
      var nameCandidate = texts.find(function (t) {
        return t.content.length > 20 && t.content.length < 80;
      });
      if (!nameCandidate) {
        nameCandidate = texts.find(function (t) { return t.content.length > 3; });
      }
      if (nameCandidate) {
        layerName = truncateAtWord(nameCandidate.content, 80);
      } else {
        layerName = truncateAtWord(texts[0].content, 80);
      }
    }

    return {
      id: layer.id,
      name: layerName,
      texts: texts,
      images: images,
      videos: videos,
      audio: audio,
      interactions: interactions,
      triggers: layerTriggers,
      // Pass through Storyline's structural hints for presentation
      isModal: layer.isModal || false,
      pausesParent: layer.pausesParent || false,
      hasContent: texts.length > 0 || images.length > 0 || videos.length > 0 || interactions.length > 0
    };
  }

  // ---- Presentation classification ----

  /**
   * Decide how a planned slide should be presented in the deep-scroll layout.
   * Options:
   *   - hero: full-viewport title slide with gradient/image background
   *   - narrative: text-heavy content with optional images (flowing paragraphs)
   *   - media-feature: large image or video as the focal point
   *   - interactive: layers with accordion/modal/bento interactions
   *   - card-grid: multiple short content blocks in a grid
   *   - form: input fields
   *   - quiz: quiz questions
   *   - branching: path selection
   *   - results: score display
   */
  function classifyPresentation(plan) {
    if (plan.type === 'title') return 'hero';
    if (plan.type === 'results') return 'results';
    if (plan.type === 'branching') return 'branching';
    if (plan.type === 'form' || plan.formFields.length > 0) return 'form';
    if (plan.quizData) return 'quiz';

    var hasLayers = plan.layers.length > 0;
    var hasVideo = plan.content.videos.length > 0;
    var hasHeroImage = plan.content.images.some(function (img) { return img.role === 'hero'; });
    var textLength = plan.content.bodyTexts.join(' ').length;

    // Lots of layers → interactive section
    if (hasLayers && plan.layers.length >= 2) {
      // Classify the interaction type
      var layerHasImages = plan.layers.some(function (l) { return l.images.length > 0; });
      var avgTextLen = plan.layers.reduce(function (sum, l) {
        return sum + l.texts.reduce(function (s, t) { return s + t.content.length; }, 0);
      }, 0) / plan.layers.length;

      // Layer interaction classification based on content characteristics:
      //
      // BENTO GRID: 3-6 layers with SHORT text (key facts, bullet points).
      //   Storyline authors use this pattern for "at a glance" information.
      //   avgTextLen < 100 and maxTextLen < 150 chars per layer.
      //
      // MODAL: Layers with images — each layer is a visual topic.
      //   Storyline authors use this for "click to explore" image galleries.
      //
      // ACCORDION: All other cases — text-heavy layers that need expansion.
      //   Storyline authors use this for detailed content that shouldn't
      //   all be visible at once.
      //
      // These thresholds come from typical Storyline content patterns:
      // - "Key fact" layers: 30-80 chars (1-2 sentences)
      // - "Detail" layers: 100-300+ chars (full paragraphs)
      // - 7+ layers is too many for a grid, always use accordion
      var maxTextLen = plan.layers.reduce(function (max, l) {
        return Math.max(max, l.texts.reduce(function (s, t) { return s + t.content.length; }, 0));
      }, 0);

      // Check if Storyline explicitly marks any layers as modal
      var hasModalLayers = plan.layers.some(function (l) { return l.isModal; });

      if (hasModalLayers) {
        // Storyline's modal flag = author intended these as overlay panels
        plan.interactionType = 'modal';
      } else if (plan.layers.length >= 3 && plan.layers.length <= 6 && avgTextLen < 100 && maxTextLen < 150) {
        plan.interactionType = 'bento';
      } else if (layerHasImages && plan.layers.length <= 8) {
        plan.interactionType = 'modal';
      } else {
        plan.interactionType = 'accordion';
      }
      return 'interactive';
    }

    // Video or large image focal point
    if (hasVideo) return 'media-feature';
    if (hasHeroImage && textLength < 200) return 'media-feature';

    // Text-heavy → narrative flow
    if (textLength > 100) return 'narrative';

    return 'standard';
  }

  // ---- Text cleaning ----

  function truncateAtWord(text, maxLen) {
    if (!text || text.length <= maxLen) return text;
    var truncated = text.substring(0, maxLen);
    var lastSpace = truncated.lastIndexOf(' ');
    if (lastSpace > maxLen * 0.6) truncated = truncated.substring(0, lastSpace);
    return truncated + '...';
  }

  function cleanTextContent(text) {
    var cleaned = text
      .replace(/\r\n/g, ' ')
      .replace(/\r/g, ' ')
      .replace(/\n/g, ' ')
      // Remove embedded icon/shape alt-text references
      // Universal Storyline pattern: "word(s) icon N" embedded in longer text
      .replace(/\b[\w\s-]*(?:icon|arrow)\s*\d+\b/gi, '')
      // Remove "Line N" references (connector shapes)
      .replace(/\bLine\s+\d+\b/g, '')
      // Remove variable placeholders
      .replace(/%_player\.\w+%/g, '')
      // Remove caret-escaped characters from Storyline: "100^%^"
      .replace(/\^([%&])\^/g, '$1')
      // Clean up extra whitespace from removals
      .replace(/\s+/g, ' ')
      .trim();

    // Strip leading player instructions from the start of long text blocks.
    // Storyline concatenates player instructions with content text.
    // Pattern: "Hover over..." or "Click on the..." followed by content.
    if (cleaned.length > 100) {
      cleaned = cleaned
        .replace(/^(Hover\s+over\s+[^.]+\.\s*)/i, '')
        .replace(/^(Click\s+on\s+the\s+button\s+[^.]+\.\s*)/i, '')
        .trim();
    }

    return cleaned;
  }

  function cleanButtonLabel(label) {
    return (label || '')
      .replace(/\r\n/g, ' ')
      .replace(/\r/g, ' ')
      .replace(/\n/g, ' ')
      .replace(/\s+/g, ' ')
      .trim();
  }

  // ---- Verification report ----

  /**
   * Build a report showing what content was found, kept, and dropped.
   */
  function buildVerification(courseIR, sections) {
    var extracted = {
      totalSlides: courseIR.slides.length,
      totalElements: 0,
      totalTexts: 0,
      totalImages: 0,
      totalVideos: 0,
      totalAudio: 0,
      totalLayers: 0,
      totalTriggers: 0,
      totalInteractions: 0,
      totalStates: 0,
      totalVariables: courseIR.variables ? courseIR.variables.length : 0
    };

    courseIR.slides.forEach(function (slide) {
      extracted.totalLayers += slide.layers.length;
      extracted.totalTriggers += slide.triggers.length;
      slide.layers.forEach(function (l) {
        extracted.totalTriggers += l.triggers.length;
      });
      slide.elements.forEach(function (el) {
        extracted.totalElements++;
        if (el.type === 'text') extracted.totalTexts++;
        if (el.type === 'image') extracted.totalImages++;
        if (el.type === 'video') extracted.totalVideos++;
        if (el.type === 'audio') extracted.totalAudio++;
        if (el.type === 'interaction') extracted.totalInteractions++;
        if (el.states && el.states.length > 0) extracted.totalStates += el.states.length;
      });
    });

    var planned = {
      totalSections: sections.length,
      totalSlides: 0,
      textsKept: 0,
      textsDropped: 0,
      imagesKept: 0,
      videosKept: 0,
      audioKept: 0,
      layersKept: 0,
      triggersKept: 0,
      interactionsKept: 0,
      statesKept: 0
    };

    sections.forEach(function (section) {
      section.slides.forEach(function (slide) {
        planned.totalSlides++;
        planned.textsKept += slide.content.headings.length + slide.content.bodyTexts.length + slide.content.callouts.length;
        planned.imagesKept += slide.content.images.length;
        planned.videosKept += slide.content.videos.length;
        planned.audioKept += slide.content.audio.length;
        planned.layersKept += slide.layers.length;
        planned.triggersKept += slide.triggers.length;
        planned.interactionsKept += slide.interactions.length;
        planned.statesKept += slide.states.length;
        slide.layers.forEach(function (l) {
          planned.triggersKept += l.triggers.length;
        });
      });
    });

    planned.textsDropped = extracted.totalTexts - planned.textsKept;

    return {
      extracted: extracted,
      planned: planned,
      contentRetention: extracted.totalElements > 0
        ? Math.round((planned.textsKept + planned.imagesKept + planned.videosKept) /
            Math.max(1, extracted.totalTexts + extracted.totalImages + extracted.totalVideos) * 100)
        : 100
    };
  }

  // ---- Main entry point ----

  /**
   * Create a CoursePlan from a CourseIR.
   * @param {object} courseIR - The raw extracted course data
   * @param {Function} log - Logging callback
   * @returns {object} CoursePlan
   */
  function planCourse(courseIR, log) {
    log('Planning course structure...');

    var sections = groupIntoSections(courseIR.slides);
    log('Identified ' + sections.length + ' sections from ' + courseIR.slides.length + ' slides');

    // Log section breakdown
    sections.forEach(function (section) {
      log('  ' + section.type.toUpperCase() + ': "' + section.title + '" (' + section.slides.length + ' slides)');
    });

    var verification = buildVerification(courseIR, sections);
    log('Content retention: ' + verification.contentRetention + '% of meaningful content preserved');
    if (verification.planned.textsDropped > 0) {
      log('  Dropped ' + verification.planned.textsDropped + ' junk/decorative text elements');
    }

    return {
      meta: courseIR.meta,
      sections: sections,
      quizBanks: courseIR.questionBanks,
      navigation: courseIR.navigation,
      variables: courseIR.variables,
      assets: courseIR.assets,
      verification: verification
    };
  }

  return { planCourse: planCourse };
})();
