/**
 * Data Builders — Converts CoursePlan into the JSON data structures
 * consumed by the generated React app.
 *
 * Now works from CoursePlan (output of ContentPlanner) instead of raw CourseIR.
 * Produces section-based data for deep-scroll layout.
 */
window.GeneratorData = (function () {
  'use strict';

  /**
   * Detect Storyline's auto-generated question/slide type labels.
   * Storyline uses its internal type name as the default slide title when
   * the author doesn't provide one. These are universal across all exports.
   */
  function isStorylineTypeLabel(text) {
    if (!text) return true;
    var t = text.trim().toLowerCase();
    // Bare numbers ("0", "1", "2") are auto-generated
    if (/^\d+$/.test(t)) return true;
    var typeLabels = [
      'pick one', 'pick many', 'pick all', 'true/false', 'true false',
      'text entry', 'matching', 'sequence', 'fill in', 'fill in the blank',
      'drag and drop', 'freeform', 'graded question', 'survey question',
      'multiple choice', 'word bank', 'hotspot', 'untitled slide'
    ];
    // Exact match or match with trailing number ("Text Entry 1")
    return typeLabels.some(function (label) {
      return t === label || t.match(new RegExp('^' + label.replace(/[.*+?^${}()|[\]\\]/g, '\\$&') + '\\s*\\d*$'));
    });
  }

  /**
   * Check if a title looks like an auto-generated section/question label.
   * Used to filter out titles like "Section 3 Q1", "Quiz 1", etc.
   */
  function isAutoGeneratedTitle(text) {
    if (!text) return true;
    var t = text.trim();
    if (/^\d+$/.test(t)) return true;
    // "Section N QN" pattern
    if (/^section\s+\d+\s+q\d+$/i.test(t)) return true;
    // "Table N" or "Table 01 Drag and Drop - X" — Storyline internal naming
    if (/^table\s+\d/i.test(t)) return true;
    // ALL CAPS internal names (Storyline authors use these for internal labels)
    if (/^[A-Z\s\/\-]{4,}$/.test(t) && t === t.toUpperCase() && t.length < 30) return true;
    return isStorylineTypeLabel(text);
  }

  /**
   * Check if a layer name looks auto-generated (e.g. "Layer 1", "Layer 2").
   * Storyline always names layers this way by default.
   */
  function isAutoLayerName(name) {
    if (!name) return true;
    return /^layer\s+\d+$/i.test(name.trim());
  }

  /**
   * Extract first meaningful sentence from an array of text strings.
   * Used to replace auto-generated layer names with actual content.
   */
  function extractFirstSentence(texts, maxLen) {
    if (!texts || texts.length === 0) return null;
    var combined = texts.join(' ').trim();
    if (!combined) return null;
    // Try to find first sentence
    var match = combined.match(/^[^.!?]+[.!?]/);
    var sentence = match ? match[0].trim() : combined;
    if (sentence.length > (maxLen || 60)) {
      sentence = sentence.substring(0, maxLen || 60).replace(/\s+\S*$/, '') + '...';
    }
    return sentence;
  }

  /**
   * Detect the best layout for a slide based on its content characteristics.
   * Used by the app renderer to choose between split, steps, narrative, etc.
   */
  function detectLayout(slide, data) {
    var hasImage = !!(data.image || (data.images && data.images.length > 0));
    var hasVideo = !!(data.video || (data.videos && data.videos && data.videos.length > 0));
    var texts = data.texts || [];
    var hasTexts = texts.length > 0;

    // If slide has image AND text, use split layout
    if (hasImage && hasTexts && !data.backgroundImage) {
      return 'split';
    }

    // If no text, only image/video, it's media-focus
    if (!hasTexts && (hasImage || hasVideo)) {
      return 'media-focus';
    }

    // If all texts are short (< 100 chars each), could be steps
    if (hasTexts && texts.length >= 2) {
      var allShort = texts.every(function (t) { return t.length < 100; });
      if (allShort && !hasImage) {
        return 'steps';
      }
    }

    // If any single text block is long (> 300 chars), it's narrative
    if (hasTexts) {
      var hasLongText = texts.some(function (t) { return t.length > 300; });
      if (hasLongText) {
        return 'narrative';
      }
    }

    return 'default';
  }

  function resolveImage(img, generatedImages) {
    if (!img) return undefined;
    var generated = generatedImages && generatedImages.entries
      ? generatedImages.entries.find(function (e) {
          return e.originalAssetId === img.assetId && (e.status === 'generated' || e.status === 'original');
        })
      : null;
    if (generated && generated.generatedPath) return generated.generatedPath;
    var filename = (img.originalPath || '').split('/').pop() || '';
    return filename ? 'assets/images/' + filename : undefined;
  }

  function resolveMediaPath(originalPath, folder) {
    var filename = (originalPath || '').split('/').pop() || '';
    return filename ? 'assets/' + folder + '/' + filename : undefined;
  }

  /**
   * Build the sections data array for the deep-scroll React app.
   */
  /**
   * Parse glossary text into term+definition pairs.
   * Storyline glossaries typically have terms as capitalized phrases
   * followed by their definitions. Common patterns:
   * - "Term Definition text..." where Term is title-cased
   * - Terms are separated by the start of the next capitalized phrase
   *
   * This is a universal pattern — glossaries in any authoring tool
   * follow this term/definition structure.
   */
  /**
   * Parse glossary text into term+definition pairs.
   *
   * Storyline glossaries have a consistent pattern:
   * "Term Definition text that starts lowercase. Next Term Another definition..."
   *
   * The key insight: terms are Title Cased or ALL CAPS, and definitions
   * start with a lowercase word or article (a, an, the, in, etc.)
   *
   * Strategy: scan through words, detect where a capitalized phrase
   * transitions to a lowercase definition.
   */
  function parseGlossaryEntries(texts) {
    if (!texts || texts.length === 0) return null;
    var combined = texts.join(' ').trim();
    if (combined.length < 200) return null;

    var entries = [];
    // Match: capitalized term (possibly with /, -, parentheses) followed by
    // a definition that starts with a lowercase word or common article
    // Term boundary: stop at capitalized words that are common English articles/prepositions
    // These are STRUCTURAL English language patterns, not content-specific
    // A term in a glossary is always a NOUN PHRASE. When we hit a word that starts
    // a SENTENCE (article, pronoun, verb), that's the definition beginning.
    var pattern = /([A-Z][A-Za-z\/\-]+(?:[\s\/\-]+(?!(?:A|An|The|In|Is|Are|Was|Has|Can|May|If|It|As|By|To|Or|No|So|Do)\s)[A-Z][A-Za-z\/\-]+)*(?:\s*\([^)]+\))?)\s+([A-Za-z][^]*?)(?=\.\s+[A-Z][A-Z]|\.\s+[A-Z][a-z]+(?:[\s\/\-]+[A-Z]|[\s\/\-]+\()|\s*$)/g;

    var match;
    while ((match = pattern.exec(combined)) !== null) {
      var term = match[1].trim();
      var def = match[2].trim().replace(/\.\s*$/, '');
      // Filter out junk: term must be 2+ chars, definition must be substantial
      if (term.length >= 2 && def.length >= 15 && term.length < 80) {
        entries.push({ term: term, definition: def });
      }
    }

    // Fallback: split on sentence boundaries and extract term + definition
    if (entries.length < 5) {
      entries = [];
      // Split on period followed by space and capital letter (sentence boundary)
      var sentences = combined.split(/\.\s+(?=[A-Z])/);
      for (var i = 0; i < sentences.length; i++) {
        var s = sentences[i].trim().replace(/\.\s*$/, '');
        if (!s || s.length < 20) continue;
        // Term is the leading capitalized phrase before the first lowercase word
        // that isn't a short connector (of, and, or, for, in, with, to)
        var termMatch = s.match(/^((?:[A-Z][A-Za-z\/\-]*(?:\s*[\(][^)]*[\)])?(?:\s+(?:of|and|or|for|in|with|to|&|\/)\s+[A-Z][A-Za-z\/\-]*|\s+[A-Z][A-Za-z\/\-]*)*))\s+(.*)/);
        if (termMatch) {
          var term = termMatch[1].trim();
          var def = termMatch[2].trim();
          if (term.length >= 2 && term.length < 80 && def.length >= 10) {
            entries.push({ term: term, definition: def });
          }
        }
      }
    }

    return entries.length >= 3 ? entries : null;
  }

  function buildSectionsData(coursePlan, images) {
    return coursePlan.sections.map(function (section) {
      var isGlossary = /glossary/i.test(section.title);

      var sectionData = {
        id: section.id,
        type: isGlossary ? 'glossary' : section.type,
        title: section.title,
        slides: section.slides.map(function (slide) {
          return buildSlideData(slide, images, coursePlan);
        })
      };

      // Parse glossary entries from text content
      if (isGlossary && sectionData.slides.length > 0) {
        var glossarySlide = sectionData.slides[0];
        var allTexts = (glossarySlide.texts || []);
        var parsed = parseGlossaryEntries(allTexts);
        if (parsed) {
          sectionData.glossaryEntries = parsed;
        }
      }

      // For assessment sections, collect ALL quiz questions from all slides
      // into a single array so the app can present one unified assessment
      if (section.type === 'assessment') {
        var allQuizQuestions = [];
        section.slides.forEach(function (slide) {
          if (slide.quizData) {
            allQuizQuestions.push({
              questionText: slide.quizData.questionText,
              questionType: slide.quizData.questionType,
              choices: slide.quizData.choices,
              correctFeedback: slide.quizData.correctFeedback,
              incorrectFeedback: slide.quizData.incorrectFeedback
            });
          }
        });
        if (allQuizQuestions.length > 0) {
          sectionData.sectionQuizQuestions = allQuizQuestions;
        }
      }

      return sectionData;
    });
  }

  /**
   * Build data for a single planned slide.
   */
  function buildSlideData(slide, images, coursePlan) {
    // Clean title — don't pass through Storyline type labels
    var cleanTitle = isAutoGeneratedTitle(slide.originalTitle) ? null : slide.originalTitle;

    var data = {
      id: slide.id,
      type: slide.type,
      presentation: slide.presentation,
      title: cleanTitle
    };

    // Text content
    if (slide.content.headings.length > 0) {
      data.headings = slide.content.headings.map(function (h) { return h.text; });
    }
    if (slide.content.bodyTexts.length > 0) {
      data.texts = slide.content.bodyTexts;
    }
    if (slide.content.callouts.length > 0) {
      data.callouts = slide.content.callouts;
    }

    // Images
    var resolvedImages = slide.content.images.map(function (img) {
      return {
        src: resolveImage(img, images),
        alt: img.altText || slide.originalTitle || '',
        role: img.role
      };
    }).filter(function (img) { return img.src; });
    if (resolvedImages.length > 0) data.images = resolvedImages;

    // Separate background images from content images.
    var bgImg = slide.content.images.find(function (img) { return img.role === 'background'; });
    var heroImg = slide.content.images.find(function (img) { return img.role === 'hero'; });
    var contentImgs = resolvedImages.filter(function (img) { return img.role !== 'background'; });

    if (bgImg) {
      data.backgroundImage = resolveImage(bgImg, images);
    }

    // Legacy: single image for backward compat
    if (heroImg) data.image = resolveImage(heroImg, images);
    if (!data.image && contentImgs.length > 0) data.image = contentImgs[0].src;

    // Override images array to exclude backgrounds
    if (contentImgs.length > 0) data.images = contentImgs;

    // Videos — resolve asset IDs to file paths when originalPath is empty.
    // Storyline stores video URLs in the global assetLib, not in individual
    // video objects. The video element only has an assetId.
    if (slide.content.videos.length > 0) {
      var courseAssets = coursePlan.assets || {};
      var videoAssets = courseAssets.videos || [];
      var imageAssets = courseAssets.images || [];

      data.videos = slide.content.videos.map(function (v) {
        var videoPath = v.originalPath;
        // If originalPath is empty, resolve from asset manifest
        if (!videoPath && v.assetId !== undefined && v.assetId !== -1) {
          var asset = videoAssets.find(function (a) { return a.id === v.assetId; });
          if (asset) videoPath = asset.originalPath;
        }
        var posterPath = v.posterPath;
        // Resolve poster from posterAssetId if available
        if (!posterPath && v.posterAssetId !== undefined) {
          var posterAsset = imageAssets.find(function (a) { return a.id === v.posterAssetId; });
          if (posterAsset) posterPath = posterAsset.originalPath;
        }
        return {
          src: resolveMediaPath(videoPath, 'media'),
          poster: posterPath ? resolveMediaPath(posterPath, 'images') : undefined,
          durationMs: v.durationMs
        };
      }).filter(function (v) { return v.src; });
      if (data.videos.length > 0) data.video = data.videos[0];
    }

    // Audio
    var allAudio = slide.content.audio.map(function (a) {
      return {
        src: resolveMediaPath(a.originalPath, 'media'),
        durationMs: a.durationMs,
        isNarration: a.isNarration || false
      };
    }).filter(function (a) { return a.src; });
    if (allAudio.length > 0) {
      data.audio = allAudio[0];
      if (allAudio.length > 1) data.allAudio = allAudio;
    }

    // Layers with full content
    if (slide.layers.length > 0) {
      data.layers = slide.layers.map(function (layer) {
        var layerTexts = layer.texts.map(function (t) { return t.content; }).filter(function (t) { return t.length > 0; });

        // Clean auto-generated layer names
        var layerName = layer.name;
        if (isAutoLayerName(layerName)) {
          var extracted = extractFirstSentence(layerTexts, 60);
          if (extracted) {
            layerName = extracted;
          }
        }

        var layerData = {
          id: layer.id,
          name: layerName,
          texts: layerTexts,
          image: layer.images.length > 0 ? resolveImage(layer.images[0], images) : undefined,
          interactions: layer.interactions.length > 0 ? layer.interactions : undefined
        };

        // Layer audio
        if (layer.audio && layer.audio.length > 0) {
          layerData.audio = layer.audio.map(function (a) {
            return { src: resolveMediaPath(a.originalPath, 'media'), durationMs: a.durationMs };
          }).filter(function (a) { return a.src; });
        }

        // Layer videos — resolve asset IDs same as slide-level videos
        if (layer.videos && layer.videos.length > 0) {
          var courseAssets = coursePlan.assets || {};
          var vAssets = courseAssets.videos || [];
          layerData.videos = layer.videos.map(function (v) {
            var videoPath = v.originalPath;
            if (!videoPath && v.assetId !== undefined && v.assetId !== -1) {
              var asset = vAssets.find(function (a) { return a.id === v.assetId; });
              if (asset) videoPath = asset.originalPath;
            }
            return { src: resolveMediaPath(videoPath, 'media') };
          }).filter(function (v) { return v.src; });
        }

        return layerData;
      // Keep layers that have ANY content: text, image, interactions, OR videos
      }).filter(function (l) { return l.texts.length > 0 || l.image || (l.interactions && l.interactions.length > 0) || (l.videos && l.videos.length > 0); });

      if (data.layers.length > 0) {
        data.interactionType = slide.interactionType || classifyInteraction(data.layers);
      } else {
        delete data.layers;
      }
    }

    // Interactions
    if (slide.interactions.length > 0) {
      data.interactions = slide.interactions;
    }

    // Element states
    if (slide.states.length > 0) {
      data.states = slide.states;
    }

    // Form fields
    if (slide.formFields.length > 0) {
      data.fields = slide.formFields.map(function (f) {
        return {
          label: f.label.trim(),
          placeholder: f.label.trim(),
          fieldType: f.fieldType,
          variableName: f.variableName
        };
      });
      data.instruction = slide.content.bodyTexts.find(function (t) {
        var lower = t.toLowerCase();
        return lower.includes('enter') || lower.includes('please') || lower.includes('fill');
      }) || 'Please fill in your details';
      var formTitle = (slide.originalTitle || '').trim();
      var isAutoTitle = !formTitle || isStorylineTypeLabel(formTitle);
      data.title = isAutoTitle ? 'Your Details' : formTitle;
    }

    // Branching
    if (slide.type === 'branching') {
      data.title = slide.originalTitle || 'Choose Your Path';

      var descriptiveTexts = slide.content.bodyTexts.filter(function (t) {
        return t.length > 20 && !t.includes('%');
      });

      var headingTexts = slide.content.headings.map(function (h) { return h.text; });

      data._descriptiveTexts = descriptiveTexts;
      data._headingTexts = headingTexts;

      var greeting = slide.content.bodyTexts.find(function (t) { return t.includes('%'); });
      if (greeting) data.greeting = greeting.replace(/%_player\.[^%]+%/g, '%name%');

      var quizBankIds = coursePlan && coursePlan.quizBanks
        ? coursePlan.quizBanks.map(function (qb) { return qb.id; })
        : [];

      if (slide.buttons && slide.buttons.length > 0) {
        var descs = data._descriptiveTexts || [];
        var heads = data._headingTexts || [];
        var combined = heads.concat(descs);
        var pairSource = (heads.length === slide.buttons.length) ? heads
          : (descs.length === slide.buttons.length) ? descs
          : (combined.length === slide.buttons.length) ? combined
          : null;

        data.options = slide.buttons.map(function (btn, idx) {
          var label = btn.label;
          var lowerLabel = label.toLowerCase();
          var quizBank;
          if (lowerLabel.includes('skip') || lowerLabel.includes('no thanks')) {
            quizBank = undefined;
          } else if (quizBankIds.length > 0) {
            quizBank = quizBankIds[Math.min(idx, quizBankIds.length - 1)];
          }
          var opt = { label: label, value: label, quizBank: quizBank };
          if (pairSource && pairSource[idx]) opt.description = pairSource[idx];
          return opt;
        });

        if (pairSource) {
          delete data.texts;
          delete data.headings;
        } else {
          if (descs.length > 0) data.texts = descs;
          if (heads.length > 0) data.headings = heads;
        }
      }

      if (quizBankIds.length > 0) {
        data.quizBankIds = quizBankIds;
      }

      if (slide.layers && slide.layers.length > 0) {
        var layerTexts = slide.layers
          .filter(function (l) { return l.texts && l.texts.length > 0; })
          .map(function (l) {
            // Deduplicate layer texts (Storyline often has same text in multiple states)
            var seen = {};
            var unique = l.texts.map(function (t) { return (typeof t === 'object' ? t.content : t) || ''; })
              .filter(function (t) {
                if (typeof t !== 'string' || !t.trim()) return false;
                var key = t.trim().toLowerCase();
                if (seen[key]) return false;
                seen[key] = true;
                return true;
              });
            return unique.join(' ');
          });

        if (layerTexts.length > 0) {
          var longestIdx = 0;
          layerTexts.forEach(function (t, i) {
            if (t.length > layerTexts[longestIdx].length) longestIdx = i;
          });

          var longestText = layerTexts[longestIdx];
          if (longestText.length > 100) {
            // Don't add if significantly overlaps with existing texts
            var existingTexts = (data.texts || []).join(' ').toLowerCase();
            var isRedundant = existingTexts.length > 50 &&
              (existingTexts.indexOf(longestText.substring(0, 50).toLowerCase()) >= 0 ||
               longestText.toLowerCase().indexOf(existingTexts.substring(0, 50)) >= 0);
            if (!isRedundant) {
              if (!data.texts) data.texts = [];
              data.texts.unshift(longestText);
            }
          }
        }
      }

      delete data._descriptiveTexts;
      delete data._headingTexts;
    }

    // Quiz
    if (slide.quizData) {
      data.quiz = {
        questionText: slide.quizData.questionText,
        questionType: slide.quizData.questionType,
        choices: slide.quizData.choices,
        correctFeedback: slide.quizData.correctFeedback,
        incorrectFeedback: slide.quizData.incorrectFeedback
      };
    }

    // Results
    if (slide.type === 'results') {
      data.title = slide.originalTitle || 'Your Results';
    }

    // Title slide extras
    if (slide.type === 'title') {
      var descriptiveTitle = slide.content.headings[0]
        ? slide.content.headings[0].text
        : (slide.content.bodyTexts[0] || slide.originalTitle);
      if (descriptiveTitle) {
        data.title = descriptiveTitle;
        var subtitleSource = slide.content.headings.length > 1
          ? slide.content.headings[1].text
          : slide.content.bodyTexts[0];
        if (subtitleSource && subtitleSource !== descriptiveTitle) {
          data.subtitle = subtitleSource;
        }
      }
    }

    // Detect content layout pattern
    if (slide.presentation === 'narrative' || slide.presentation === 'media-feature' || !slide.presentation) {
      data.layout = detectLayout(slide, data);
    }

    // Final text cleanup: remove internal repetition from all text entries.
    // This catches repeated content from Storyline states/layers that survived
    // through any code path (bodyTexts, layer context, branching descriptions).
    if (data.texts && data.texts.length > 0) {
      data.texts = data.texts.map(function (t) {
        return typeof t === 'string' ? removeInternalRepetition(t) : t;
      }).filter(function (t) { return t && (typeof t === 'string' ? t.trim().length > 0 : true); });
    }

    return data;
  }

  /**
   * Remove internally repeated content within a text block.
   * Uses normalized word comparison to handle special characters (em dashes, etc.)
   */
  function removeInternalRepetition(text) {
    if (!text || text.length < 100) return text;
    var words = text.split(/\s+/);
    var normalized = words.map(function (w) {
      return w.toLowerCase().replace(/[^\w]/g, '');
    }).filter(function (w) { return w.length > 0; });
    if (normalized.length < 12) return text;
    var windowSize = 6;
    var phraseSeen = {};
    var cutIndex = -1;
    for (var i = 0; i <= normalized.length - windowSize; i++) {
      var phrase = normalized.slice(i, i + windowSize).join(' ');
      if (phraseSeen[phrase] !== undefined && i - phraseSeen[phrase] >= windowSize) {
        cutIndex = i;
        break;
      }
      if (phraseSeen[phrase] === undefined) phraseSeen[phrase] = i;
    }
    if (cutIndex > 0) {
      var origWords = text.split(/\s+/);
      var nc = 0;
      for (var wi = 0; wi < origWords.length; wi++) {
        var nw = origWords[wi].toLowerCase().replace(/[^\w]/g, '');
        if (nw.length > 0) {
          if (nc >= cutIndex) return origWords.slice(0, wi).join(' ');
          nc++;
        }
      }
    }
    return text;
  }

  /**
   * Classify how layers should be rendered.
   */
  function classifyInteraction(layers) {
    if (!layers || layers.length === 0) return null;
    var hasImages = layers.some(function (l) { return l.image; });
    var avgTextLen = layers.reduce(function (sum, l) {
      return sum + (l.texts ? l.texts.join(' ').length : 0);
    }, 0) / layers.length;
    if (layers.length >= 3 && avgTextLen < 200) return 'bento';
    if (hasImages) return 'modal';
    return 'accordion';
  }

  /**
   * Build quiz bank data (unchanged — quiz banks are already clean).
   */
  function buildQuizData(coursePlan) {
    return (coursePlan.quizBanks || []).map(function (bank) {
      return {
        id: bank.id,
        title: bank.title,
        group: bank.group,
        drawCount: bank.drawCount,
        questions: bank.questions.map(function (q) {
          return {
            questionText: q.questionText,
            questionType: q.questionType,
            choices: q.choices.map(function (c) { return { text: c.text, isCorrect: c.isCorrect }; }),
            correctFeedback: q.correctFeedback,
            incorrectFeedback: q.incorrectFeedback
          };
        })
      };
    });
  }

  return { buildSectionsData: buildSectionsData, buildQuizData: buildQuizData };
})();
