#!/usr/bin/env node
/**
 * V5 Course Builder — Preact SSR + Tailwind v4
 *
 * Orchestrator: loads design-tokens.json + course-layout.json, delegates
 * all HTML rendering to Preact SSR (dist/render.cjs), compiles Tailwind v4
 * CSS, and assembles the final single-file course.html.
 *
 * All 28 component types × 56 variants are rendered by Preact — one
 * rendering path, no parallel fill functions. Variant templates for the
 * authoring layer are generated by renderComponentVariant() in render.tsx.
 *
 * Usage: node engine/scripts/build-course.js
 */

const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

const ROOT = path.resolve(__dirname, '..', '..');
const TOKENS_PATH      = path.resolve(ROOT, 'engine/output/design-tokens.json');
const LAYOUT_PATH      = path.resolve(ROOT, 'engine/output/course-layout.json');
const HYDRATE_PATH     = path.resolve(ROOT, 'engine/scripts/hydrate.js');
const OUTPUT_PATH      = path.resolve(ROOT, 'engine/output/course.html');
const PAGES_PATH       = path.resolve(ROOT, 'index.html');
const ARCHETYPES_PATH  = path.resolve(ROOT, 'engine/schemas/visual-archetypes.json');
const THEME_TEMPLATE   = path.resolve(ROOT, 'src/theme-template.css');
const THEME_OUTPUT     = path.resolve(ROOT, 'engine/output/theme.css');
const BRAND_SPEC_PATH  = path.resolve(ROOT, 'engine/output/brand-spec.json');
const CSS_OUTPUT       = path.resolve(ROOT, 'engine/output/course.css');

// Archetype Recipe object — resolved from visual-archetypes.json + tokens.archetype.
// Replaces the old DC (design-contract) global. Set in buildArchetypeRecipe().
let AR = {};

// Theme flag — set from design-tokens.json in main(). Used by fill functions
// to ensure text colours are readable on dark or light backgrounds.
let IS_DARK = true;

// ─── Archetype recipe builder ─────────────────────────────────────────
/**
 * Load visual-archetypes.json, resolve the correct recipe for the given
 * archetype name (falling back to tech-modern), apply any _extends chain,
 * and return the flat recipe object.
 */
function buildArchetypeRecipe(archetypeName) {
  let defs;
  try {
    defs = JSON.parse(fs.readFileSync(ARCHETYPES_PATH, 'utf-8'));
  } catch (e) {
    console.warn('[archetype] Could not load visual-archetypes.json — using empty recipe');
    return {};
  }

  const archetypes = defs.archetypes || {};

  // Resolve with _extends chain (one level deep is enough for our schema)
  function resolve(name) {
    const recipe = archetypes[name];
    if (!recipe) return archetypes['tech-modern'] || {};
    if (recipe._extends) {
      const base = archetypes[recipe._extends] || {};
      // Deep merge: base first, then recipe (recipe wins), excluding meta keys
      const merged = JSON.parse(JSON.stringify(base));
      for (const [k, v] of Object.entries(recipe)) {
        if (k.startsWith('_')) continue;
        if (v && typeof v === 'object' && !Array.isArray(v) && merged[k] && typeof merged[k] === 'object') {
          merged[k] = { ...merged[k], ...v };
        } else {
          merged[k] = v;
        }
      }
      // Apply _overrides if present (dot-path notation: "surface.card")
      if (recipe._overrides) {
        for (const [dotPath, val] of Object.entries(recipe._overrides)) {
          const parts = dotPath.split('.');
          let obj = merged;
          for (let i = 0; i < parts.length - 1; i++) {
            if (!obj[parts[i]]) obj[parts[i]] = {};
            obj = obj[parts[i]];
          }
          obj[parts[parts.length - 1]] = val;
        }
      }
      return merged;
    }
    return recipe;
  }

  const name = archetypeName || 'tech-modern';
  const recipe = resolve(name);
  console.log(`[archetype] Using recipe: ${name} (surface: ${recipe.surface?.style || 'unknown'})`);
  return recipe;
}

// ─── HTML helpers ────────────────────────────────────────────────────
function esc(s) {
  if (!s) return '';
  return String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}

function embedImage(imagePath) {
  if (!imagePath) return '';
  if (imagePath.startsWith('data:') || imagePath.startsWith('http')) return imagePath;
  const fullPath = path.resolve(ROOT, 'engine/output', imagePath);
  if (!fs.existsSync(fullPath)) return imagePath;
  const buffer = fs.readFileSync(fullPath);
  const ext = path.extname(fullPath).toLowerCase();
  const mimeMap = { '.jpg': 'image/jpeg', '.jpeg': 'image/jpeg', '.png': 'image/png', '.gif': 'image/gif', '.webp': 'image/webp', '.svg': 'image/svg+xml' };
  return `data:${mimeMap[ext] || 'image/jpeg'};base64,${buffer.toString('base64')}`;
}

// ─── Typography parsing — converts Tailwind classes to CSS values ────
const TW_SIZE_MAP = {
  'text-xs': '0.75rem', 'text-sm': '0.875rem', 'text-base': '1rem',
  'text-lg': '1.125rem', 'text-xl': '1.25rem', 'text-2xl': '1.5rem',
  'text-3xl': '1.875rem', 'text-4xl': '2.25rem', 'text-5xl': '3rem',
  'text-6xl': '3.75rem', 'text-7xl': '4.5rem', 'text-8xl': '6rem',
};
const TW_WEIGHT_MAP = {
  'font-thin': '100', 'font-extralight': '200', 'font-light': '300',
  'font-normal': '400', 'font-medium': '500', 'font-semibold': '600',
  'font-bold': '700', 'font-extrabold': '800', 'font-black': '900',
};
const TW_LEADING_MAP = {
  'leading-none': '1', 'leading-tight': '1.25', 'leading-snug': '1.375',
  'leading-normal': '1.5', 'leading-relaxed': '1.625', 'leading-loose': '2',
};
const TW_TRACKING_MAP = {
  'tracking-tighter': '-0.05em', 'tracking-tight': '-0.025em',
  'tracking-normal': '0em', 'tracking-wide': '0.025em',
  'tracking-wider': '0.05em', 'tracking-widest': '0.1em',
};

/** Parse Tailwind typography class string into CSS values */
function parseTypoClasses(classStr) {
  if (!classStr) return {};
  const result = {};
  for (const p of classStr.split(/\s+/)) {
    // Custom values: text-[10px], leading-[0.9], tracking-[0.2em]
    let m;
    if ((m = p.match(/^text-\[(.+)\]$/))) { result.fontSize = m[1]; continue; }
    if ((m = p.match(/^leading-\[(.+)\]$/))) { result.lineHeight = m[1]; continue; }
    if ((m = p.match(/^tracking-\[(.+)\]$/))) { result.letterSpacing = m[1]; continue; }
    // Responsive desktop override: md:text-8xl → fontSizeDesktop
    if ((m = p.match(/^md:text-(.+)$/))) {
      const mapped = TW_SIZE_MAP[`text-${m[1]}`];
      if (mapped) result.fontSizeDesktop = mapped;
      continue;
    }
    // Standard mappings
    if (TW_SIZE_MAP[p]) { result.fontSize = TW_SIZE_MAP[p]; continue; }
    if (TW_WEIGHT_MAP[p]) { result.fontWeight = TW_WEIGHT_MAP[p]; continue; }
    if (TW_LEADING_MAP[p]) { result.lineHeight = TW_LEADING_MAP[p]; continue; }
    if (TW_TRACKING_MAP[p]) { result.letterSpacing = TW_TRACKING_MAP[p]; continue; }
  }
  return result;
}

/** Merge brand weight with engine defaults. Brand controls font-weight character
 *  (bold vs light), engine controls sizes/line-heights/tracking for consistency. */
function mergeTypo(brand, defaults) {
  const b = parseTypoClasses(brand || '');
  const d = parseTypoClasses(defaults);
  // Only take fontWeight from brand — size, lineHeight, letterSpacing are ours
  return { ...d, ...(b.fontWeight ? { fontWeight: b.fontWeight } : {}) };
}

/** Build Tailwind fontSize config entry string: ["size", { lineHeight, fontWeight, ... }]
 *  Used only by generateHead() CDN fallback — kept for --tw-cdn compatibility. */
function fzEntry(t) {
  const cfg = {};
  if (t.lineHeight) cfg.lineHeight = t.lineHeight;
  if (t.letterSpacing) cfg.letterSpacing = t.letterSpacing;
  if (t.fontWeight) cfg.fontWeight = t.fontWeight;
  return `["${t.fontSize}", ${JSON.stringify(cfg)}]`;
}

// ─── Generate <head> — CDN fallback (only used with --tw-cdn flag) ────
// Legacy path: loads Tailwind from CDN with inline config.
// Active path is generateHeadV4() which uses compiled Tailwind v4 CSS.
function generateHead(tokens, courseTitle) {
  const colors = tokens.colors || {};
  const fonts = tokens.fonts || {};
  const isDark = tokens.isDark !== false;

  // Build Tailwind color config from tokens
  const colorEntries = Object.entries(colors)
    .map(([k, v]) => `                        "${k}": "${v}"`)
    .join(',\n');

  // Font families
  const headlineFont = fonts.headline || 'Inter';
  const bodyFont = fonts.body || 'Inter';
  const labelFont = fonts.label || bodyFont;

  // Google Fonts URL — request both font families with useful weights
  const fontFamilies = [...new Set([headlineFont, bodyFont, labelFont])];
  const googleFontsUrl = 'https://fonts.googleapis.com/css2?' +
    fontFamilies.map(f => `family=${f.replace(/ /g, '+')}:wght@100;200;300;400;500;600;700;800;900`).join('&') +
    '&display=swap';

  // ── Typography scale — brand weight + engine defaults ────────────
  // Brand provides weight preference, engine controls sizes/spacing.
  const typo = tokens.typography || {};
  const T = {
    display:   mergeTypo(typo.h1,         'text-5xl font-bold tracking-tighter leading-[1.15]'),
    h2:        mergeTypo(typo.h2,         'text-3xl font-semibold leading-snug'),
    h3:        mergeTypo(typo.h3,         'text-xl font-semibold leading-snug'),
    h4:        (() => {
      // Guard: if brand h4 is tiny (< 1rem), fall back to engine default for card titles
      const merged = mergeTypo(typo.h4, 'text-base font-medium leading-normal');
      const size = parseFloat(merged.fontSize) || 0;
      if (size > 0 && size < 1) return mergeTypo('', 'text-base font-medium leading-normal');
      return merged;
    })(),
    bodyLg:    mergeTypo(typo.bodyLarge,   'text-sm font-light leading-normal'),
    body:      mergeTypo(typo.body,        'text-sm leading-normal'),
    label:     mergeTypo(typo.label,       'text-xs font-medium tracking-widest'),
    blockquote: mergeTypo(typo.blockquote, 'text-2xl font-light leading-relaxed'),
    stat:      mergeTypo(typo.statNumber,  'text-4xl font-extrabold'),
  };

  // Desktop display size (hero h1 responsive step-up)
  // If brand provided a desktop size, use it; otherwise scale up ~1.5x from base
  const displayXlSize = T.display.fontSizeDesktop || (() => {
    const base = parseFloat(T.display.fontSize) || 3;
    return (base * 1.5).toFixed(2) + 'rem';
  })();
  const displayXl = `"display-xl": ${fzEntry({ ...T.display, fontSize: displayXlSize })},`;

  // Build fontSize config for Tailwind
  const fontSizeEntries = `
                    "display": ${fzEntry(T.display)},
                    ${displayXl}
                    "h2": ${fzEntry(T.h2)},
                    "h3": ${fzEntry(T.h3)},
                    "h4": ${fzEntry(T.h4)},
                    "body-lg": ${fzEntry(T.bodyLg)},
                    "body": ${fzEntry(T.body)},
                    "label-text": ${fzEntry(T.label)},
                    "blockquote": ${fzEntry(T.blockquote)},
                    "stat": ${fzEntry(T.stat)}`;

  // Derive key colours for custom CSS definitions
  const bg = colors['background'] || '#131313';
  const onSurface = colors['on-surface'] || '#e2e2e2';
  const surfaceContainer = colors['surface-container'] || '#1f1f1f';
  const outlineVariant = colors['outline-variant'] || '#474747';
  const primary = colors['primary'] || '#ffffff';
  const onPrimary = colors['on-primary'] || '#000000';
  const primaryContainer = colors['primary-container'] || '#d4d4d4';
  const onPrimaryContainer = colors['on-primary-container'] || '#000000';
  const secondary = colors['secondary'] || '#adc6ff';
  const tertiary = colors['tertiary'] || '#e9ddff';
  const surfaceContainerHigh = colors['surface-container-high'] || '#2a2a2a';

  return `<meta charset="utf-8"/>
<meta content="width=device-width, initial-scale=1.0" name="viewport"/>
<title>${esc(courseTitle)}</title>

<!-- Tailwind CDN -->
<script src="https://cdn.tailwindcss.com?plugins=forms,container-queries"></script>

<!-- Google Fonts -->
<link href="${googleFontsUrl}" rel="stylesheet"/>

<!-- Material Symbols -->
<link href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:wght,FILL@100..700,0..1&display=swap" rel="stylesheet"/>

<!-- GSAP + ScrollTrigger (scroll animations) -->
<script src="https://cdn.jsdelivr.net/npm/gsap@3.12.7/dist/gsap.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/gsap@3.12.7/dist/ScrollTrigger.min.js"></script>

<!-- SplitType (text line reveals) -->
<script src="https://cdn.jsdelivr.net/npm/split-type@0.3.4/umd/index.min.js"></script>

<!-- Tailwind Config — colours + fonts from design-tokens.json -->
<script>
    tailwind.config = {
        darkMode: "class",
        theme: {
            extend: {
                colors: {
${colorEntries}
                },
                fontFamily: {
                    "headline": ["${headlineFont}"],
                    "body": ["${bodyFont}"],
                    "label": ["${labelFont}"]
                },
                fontSize: {${fontSizeEntries}
                },
                borderRadius: {"DEFAULT": "1rem", "lg": "2rem", "xl": "3rem", "full": "9999px"},
            },
        },
    }
</script>

<!-- Custom classes -->
<style>
    /* Base */
    body { background-color: ${bg}; color: ${onSurface}; font-family: '${bodyFont}', sans-serif; }
    .material-symbols-outlined { font-variation-settings: 'FILL' 0, 'wght' 400, 'GRAD' 0, 'opsz' 24; }

    /* Glass card — frosted surface panel */
    .glass-card {
        background: ${surfaceContainer}cc;
        backdrop-filter: blur(16px);
        -webkit-backdrop-filter: blur(16px);
        border: 1px solid ${outlineVariant}26;
    }

    /* Glass — lighter variant for tables/containers */
    .glass {
        background: ${surfaceContainer}99;
        backdrop-filter: blur(8px);
        -webkit-backdrop-filter: blur(8px);
    }

    /* Glass nav */
    .glass-nav {
        backdrop-filter: blur(20px);
        -webkit-backdrop-filter: blur(20px);
        border-bottom: 1px solid ${outlineVariant}26;
    }

    /* Text gradient — brand gradient on text */
    .text-gradient {
        background: linear-gradient(135deg, ${primary}, ${secondary}, ${tertiary});
        -webkit-background-clip: text;
        -webkit-text-fill-color: transparent;
        background-clip: text;
    }

    /* Primary button */
    .btn-primary {
        background: ${primary};
        color: ${onPrimary};
        transition: opacity 0.2s, transform 0.2s;
    }
    .btn-primary:hover { opacity: 0.85; transform: translateY(-1px); }

    /* Scroll progress bar (injected by hydrate.js as #hydrate-progress) */
    #hydrate-progress {
        background: linear-gradient(90deg, ${secondary}, ${primary}) !important;
    }

    /* Nav drawer */
    .nav-drawer { scrollbar-width: thin; }
    .drawer-link-active .drawer-index { color: ${primary}; }

    /* Utility: hide details marker */
    details summary::-webkit-details-marker { display: none; }

    /* Custom scrollbar */
    .custom-scrollbar::-webkit-scrollbar { width: 4px; }
    .custom-scrollbar::-webkit-scrollbar-track { background: ${colors['surface-container-lowest'] || '#0e0e0e'}; }
    .custom-scrollbar::-webkit-scrollbar-thumb { background: ${colors['surface-variant'] || '#353535'}; border-radius: 10px; }

    /* Scroll animation initial states — hidden until GSAP reveals */
    [data-animate] { opacity: 0; }
    [data-animate="fade-up"] { transform: translateY(80px); }
    [data-animate="slide-in-left"] { transform: translateX(-120px); }
    [data-animate="slide-in-right"] { transform: translateX(120px); }
    [data-animate="scale-in"] { transform: scale(0.8); }
    [data-animate="clip-up"] { clip-path: inset(100% 0% 0% 0%); opacity: 1; }
    /* Hero is always visible (above fold) */
    [data-component-type="hero"] { opacity: 1 !important; transform: none !important; }
    [data-component-type="hero"] [data-animate] { opacity: 0; }
    /* Reduced motion: show everything immediately */
    @media (prefers-reduced-motion: reduce) {
      [data-animate] { opacity: 1 !important; transform: none !important; clip-path: none !important; }
    }



    /* Containment safety net */
    html, body { overflow-x: hidden; }
    img, video, iframe { max-width: 100%; }
    .line-clamp-4 { display: -webkit-box; -webkit-line-clamp: 4; -webkit-box-orient: vertical; overflow: hidden; }

    /* Course gate — blurred preview until path selection is made */
    [data-course-gate].gated {
        position: relative;
        max-height: 60vh;
        overflow: hidden;
        pointer-events: none;
        filter: blur(6px) saturate(0.5);
        opacity: 0.3;
        transition: filter 0.6s ease, opacity 0.6s ease, max-height 0.6s ease;
    }
    [data-course-gate].gated::after {
        content: '';
        position: absolute;
        bottom: 0; left: 0; right: 0;
        height: 200px;
        background: linear-gradient(to bottom, transparent, ${bg});
        pointer-events: none;
    }
    [data-course-gate]:not(.gated) {
        transition: filter 0.6s ease, opacity 0.6s ease, max-height 0.6s ease;
        max-height: none;
        filter: none;
        opacity: 1;
    }

    /* Section progress tracker */
    [data-section-gate] .section-lock-icon { display: inline; }
    [data-section-gate].section-complete .section-lock-icon { display: none; }
    [data-section-gate].section-complete .section-check-icon { display: inline; }
    [data-section-gate]:not(.section-complete) .section-check-icon { display: none; }

    /* Smooth card hover lift */
    .hover-lift { transition: transform 0.2s ease, box-shadow 0.2s ease; }
    .hover-lift:hover { transform: translateY(-2px); }

    /* Data table improved styling */
    table th { text-align: left; }

    /* Textarea focus glow */
    textarea:focus { box-shadow: 0 0 0 3px ${secondary}20; }

    /* Smooth section transitions */
    section { transition: opacity 0.3s ease; }

    /* Better form checkboxes */
    input[type="checkbox"]:checked { background-color: ${secondary}; border-color: ${secondary}; }
</style>`;
}

// ═══════════════════════════════════════════════════════════════════════
// TAILWIND v4 — build theme CSS from tokens and compile
// ═══════════════════════════════════════════════════════════════════════

/**
 * Build a resolved theme.css from the template + design tokens, then
 * compile with Tailwind v4 CLI. Returns the compiled CSS string.
 *
 * Flow: template → resolved theme.css → Tailwind CLI → course.css → inline
 */
function buildTailwindCSS(tokens) {
  const colors = tokens.colors || {};
  const fonts = tokens.fonts || {};
  const typo = tokens.typography || {};

  // ── Typography scale — single source of truth ──────────────────────
  const T = {
    display:   mergeTypo(typo.h1,         'text-5xl font-bold tracking-tighter leading-[1.15]'),
    h2:        mergeTypo(typo.h2,         'text-3xl font-semibold leading-snug'),
    h3:        mergeTypo(typo.h3,         'text-xl font-semibold leading-snug'),
    h4:        (() => {
      const merged = mergeTypo(typo.h4, 'text-base font-medium leading-normal');
      const size = parseFloat(merged.fontSize) || 0;
      if (size > 0 && size < 1) return mergeTypo('', 'text-base font-medium leading-normal');
      return merged;
    })(),
    bodyLg:    mergeTypo(typo.bodyLarge,   'text-sm font-light leading-normal'),
    body:      mergeTypo(typo.body,        'text-sm leading-normal'),
    label:     mergeTypo(typo.label,       'text-xs font-medium tracking-widest'),
    blockquote: mergeTypo(typo.blockquote, 'text-2xl font-light leading-relaxed'),
    stat:      mergeTypo(typo.statNumber,  'text-4xl font-extrabold'),
  };

  const displayXlSize = T.display.fontSizeDesktop || (() => {
    const base = parseFloat(T.display.fontSize) || 3;
    return (base * 1.5).toFixed(2) + 'rem';
  })();

  // ── Color CSS vars for @theme ──────────────────────────────────────
  const colorVars = Object.entries(colors)
    .map(([k, v]) => `  --color-${k}: ${v};`)
    .join('\n');

  // ── Key color values for custom classes ────────────────────────────
  const bg = colors['background'] || '#131313';
  const onSurface = colors['on-surface'] || '#e2e2e2';
  const surfaceContainer = colors['surface-container'] || '#1f1f1f';
  const outlineVariant = colors['outline-variant'] || '#474747';
  const primary = colors['primary'] || '#ffffff';
  const onPrimary = colors['on-primary'] || '#000000';
  const primaryContainer = colors['primary-container'] || '#d4d4d4';
  const onPrimaryContainer = colors['on-primary-container'] || '#000000';
  const secondary = colors['secondary'] || '#adc6ff';
  const tertiary = colors['tertiary'] || '#e9ddff';
  const surfaceContainerLowest = colors['surface-container-lowest'] || '#0e0e0e';
  const surfaceVariant = colors['surface-variant'] || '#353535';

  // ── Read and resolve template ──────────────────────────────────────
  let template = fs.readFileSync(THEME_TEMPLATE, 'utf-8');

  const replacements = {
    '{{COLOR_VARS}}': colorVars,
    '{{HEADLINE_FONT}}': fonts.headline || 'Inter',
    '{{BODY_FONT}}': fonts.body || 'Inter',
    '{{LABEL_FONT}}': fonts.label || fonts.body || 'Inter',
    '{{DISPLAY_SIZE}}': T.display.fontSize,
    '{{DISPLAY_XL_SIZE}}': displayXlSize,
    '{{DISPLAY_LH}}': T.display.lineHeight || '1.15',
    '{{DISPLAY_FW}}': T.display.fontWeight || '700',
    '{{DISPLAY_LS}}': T.display.letterSpacing || '-0.05em',
    '{{H2_SIZE}}': T.h2.fontSize,
    '{{H2_LH}}': T.h2.lineHeight || '1.375',
    '{{H2_FW}}': T.h2.fontWeight || '600',
    '{{H3_SIZE}}': T.h3.fontSize,
    '{{H3_LH}}': T.h3.lineHeight || '1.375',
    '{{H3_FW}}': T.h3.fontWeight || '600',
    '{{H4_SIZE}}': T.h4.fontSize,
    '{{H4_LH}}': T.h4.lineHeight || '1.5',
    '{{H4_FW}}': T.h4.fontWeight || '500',
    '{{BODY_LG_SIZE}}': T.bodyLg.fontSize,
    '{{BODY_LG_LH}}': T.bodyLg.lineHeight || '1.625',
    '{{BODY_LG_FW}}': T.bodyLg.fontWeight || '300',
    '{{BODY_SIZE}}': T.body.fontSize,
    '{{BODY_LH}}': T.body.lineHeight || '1.625',
    '{{LABEL_SIZE}}': T.label.fontSize,
    '{{LABEL_FW}}': T.label.fontWeight || '500',
    '{{LABEL_LS}}': T.label.letterSpacing || '0.1em',
    '{{BLOCKQUOTE_SIZE}}': T.blockquote.fontSize,
    '{{BLOCKQUOTE_LH}}': T.blockquote.lineHeight || '1.625',
    '{{BLOCKQUOTE_FW}}': T.blockquote.fontWeight || '300',
    '{{STAT_SIZE}}': T.stat.fontSize,
    '{{STAT_FW}}': T.stat.fontWeight || '800',
    '{{BG}}': bg,
    '{{ON_SURFACE}}': onSurface,
    '{{SURFACE_CONTAINER}}': surfaceContainer,
    '{{OUTLINE_VARIANT}}': outlineVariant,
    '{{PRIMARY}}': primary,
    '{{ON_PRIMARY}}': onPrimary,
    '{{PRIMARY_CONTAINER}}': primaryContainer,
    '{{ON_PRIMARY_CONTAINER}}': onPrimaryContainer,
    '{{SECONDARY}}': secondary,
    '{{TERTIARY}}': tertiary,
    '{{SURFACE_CONTAINER_LOWEST}}': surfaceContainerLowest,
    '{{SURFACE_VARIANT}}': surfaceVariant,
    '{{ON_BACKGROUND}}': onSurface,
    '{{CARD_SURFACE}}': surfaceContainer,
  };

  for (const [placeholder, value] of Object.entries(replacements)) {
    template = template.split(placeholder).join(value);
  }

  // Write resolved theme.css
  fs.writeFileSync(THEME_OUTPUT, template, 'utf-8');
  console.log(`[ok] Resolved theme.css (${template.length} chars)`);

  // ── Run Tailwind v4 CLI ────────────────────────────────────────────
  // Scan the course HTML (which must already be built) + Preact components for classes
  try {
    execSync(
      `npx @tailwindcss/cli -i "${THEME_OUTPUT}" -o "${CSS_OUTPUT}" --minify`,
      { cwd: ROOT, stdio: 'pipe', timeout: 30000 }
    );
  } catch (e) {
    console.error('[ERROR] Tailwind CSS compilation failed:', e.stderr?.toString() || e.message);
    process.exit(1);
  }

  const css = fs.readFileSync(CSS_OUTPUT, 'utf-8');
  console.log(`[ok] Tailwind v4 compiled CSS (${(css.length / 1024).toFixed(0)} KB)`);
  return css;
}

/**
 * Generate <head> for Tailwind v4 builds — compiled CSS inline, no CDN.
 */
function generateHeadV4(tokens, courseTitle, compiledCSS) {
  const fonts = tokens.fonts || {};
  const headlineFont = fonts.headline || 'Inter';
  const bodyFont = fonts.body || 'Inter';
  const labelFont = fonts.label || bodyFont;

  const fontFamilies = [...new Set([headlineFont, bodyFont, labelFont])];
  const googleFontsUrl = 'https://fonts.googleapis.com/css2?' +
    fontFamilies.map(f => `family=${f.replace(/ /g, '+')}:wght@100;200;300;400;500;600;700;800;900`).join('&') +
    '&display=swap';

  return `<meta charset="utf-8"/>
<meta content="width=device-width, initial-scale=1.0" name="viewport"/>
<title>${esc(courseTitle)}</title>

<!-- Google Fonts -->
<link href="${googleFontsUrl}" rel="stylesheet"/>

<!-- Material Symbols -->
<link href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:wght,FILL@100..700,0..1&display=swap" rel="stylesheet"/>

<!-- GSAP + ScrollTrigger (scroll animations) -->
<script src="https://cdn.jsdelivr.net/npm/gsap@3.12.7/dist/gsap.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/gsap@3.12.7/dist/ScrollTrigger.min.js"></script>

<!-- SplitType (text line reveals) -->
<script src="https://cdn.jsdelivr.net/npm/split-type@0.3.4/umd/index.min.js"></script>

<!-- Compiled Tailwind v4 CSS — deterministic, no CDN dependency -->
<style>
${compiledCSS}
</style>`;
}

// ─── Category map: component type → category (for authoring panel metadata) ──
const CATEGORY_MAP = {
  'text': 'Text', 'pullquote': 'Text', 'callout': 'Text', 'key-term': 'Text',
  'graphic': 'Image', 'graphic-text': 'Image', 'full-bleed': 'Image', 'image-gallery': 'Image',
  'accordion': 'Explore', 'tabs': 'Explore', 'narrative': 'Explore',
  'flashcard': 'Explore', 'labeled-image': 'Explore',
  'mcq': 'Quiz', 'branching': 'Quiz', 'textinput': 'Quiz', 'checklist': 'Quiz',
  'stat-callout': 'Layout', 'bento': 'Layout', 'comparison': 'Layout', 'data-table': 'Layout',
  'timeline': 'Layout', 'process-flow': 'Layout',
  'media': 'Media', 'video-transcript': 'Media',
  'hero': 'Structure', 'divider': 'Structure', 'path-selector': 'Structure',
};

// ═══════════════════════════════════════════════════════════════════════
// PREACT SSR RENDERER — loaded from compiled dist/render.cjs
// ═══════════════════════════════════════════════════════════════════════
const PREACT_SSR_PATH = path.resolve(ROOT, 'dist/render.cjs');

// ═══════════════════════════════════════════════════════════════════════
// MAIN BUILD
// ═══════════════════════════════════════════════════════════════════════
function build() {
  console.log('V5 Course Builder — Preact SSR');
  console.log('===========================================\n');

  // Read inputs
  if (!fs.existsSync(LAYOUT_PATH)) {
    console.error('ERROR: course-layout.json not found');
    process.exit(1);
  }
  const layout = JSON.parse(fs.readFileSync(LAYOUT_PATH, 'utf-8'));
  console.log(`[ok] Loaded course-layout.json (${layout.sections.length} sections)`);

  // Load design tokens — the ONLY source for colours/fonts in the <head>
  if (!fs.existsSync(TOKENS_PATH)) {
    console.error('ERROR: design-tokens.json not found. Run generate-design-tokens.js first.');
    process.exit(1);
  }
  const tokens = JSON.parse(fs.readFileSync(TOKENS_PATH, 'utf-8'));
  IS_DARK = tokens.isDark !== false;
  console.log(`[ok] Loaded design-tokens.json (${Object.keys(tokens.colors || {}).length} colours, fonts: ${tokens.fonts?.headline}/${tokens.fonts?.body}, isDark: ${tokens.isDark})`);

  // ── Build archetype recipe ─────────────────────────────────────────────
  const archetypeName = tokens.archetype?.name || 'tech-modern';
  AR = buildArchetypeRecipe(archetypeName);
  console.log(`[ok] Archetype recipe built: ${archetypeName} (confidence: ${tokens.archetype?.confidence ?? 'n/a'})`);

  // ── Render sections (Preact SSR — single rendering path) ───────────────
  if (!fs.existsSync(PREACT_SSR_PATH)) {
    console.error('ERROR: dist/render.cjs not found. Run `npx vite build` first.');
    process.exit(1);
  }
  const { renderCourseBody } = require(PREACT_SSR_PATH);
  // Load brand-spec.json for colorStrategy (if it exists)
  let colorStrategy = null;
  if (fs.existsSync(BRAND_SPEC_PATH)) {
    try {
      const brandSpec = JSON.parse(fs.readFileSync(BRAND_SPEC_PATH, 'utf-8'));
      colorStrategy = brandSpec.colorStrategy || null;
      if (colorStrategy) console.log(`[ok] Loaded colorStrategy from brand-spec.json (accentSectionBg: ${colorStrategy.accentSectionBg}, cardsOnAccentBg: ${colorStrategy.cardsOnAccentBg})`);
    } catch (e) {
      console.warn('[warn] Could not load brand-spec.json for colorStrategy');
    }
  }
  const { sectionsHtml: sectionsHtmlStr, navHtml, filledCount, fallbackCount } = renderCourseBody(layout, {
    AR,
    isDark: IS_DARK,
    embedImage,
    colorStrategy,
  });

  console.log(`[ok] Rendered ${filledCount} components (${fallbackCount} fallbacks)`);

  // ── Template library: pre-render placeholder for each component type ──
  const { renderComponentVariant } = require(PREACT_SSR_PATH);
  // SVG placeholder image (grey box with image icon) as data URI
  const PH_IMG = "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='800' height='500' fill='none'%3E%3Crect width='800' height='500' rx='8' fill='%23374151'/%3E%3Cpath d='M370 230h60v8h-60z' fill='%236B7280'/%3E%3Ccircle cx='385' cy='215' r='12' fill='%236B7280'/%3E%3Cpath d='M365 260l20-25 15 18 10-10 25 30H365z' fill='%236B7280'/%3E%3Ctext x='400' y='290' text-anchor='middle' fill='%239CA3AF' font-family='sans-serif' font-size='14'%3EPlaceholder Image%3C/text%3E%3C/svg%3E";
  const PH_GFX = { large: PH_IMG, alt: 'Placeholder image' };
  const PLACEHOLDER_DATA = {
    hero:            { type:'hero', displayTitle:'Your Heading Here', body:'<p>Enter your introduction text here.</p>', _graphic: PH_GFX },
    text:            { type:'text', displayTitle:'Your Heading Here', body:'<p>Enter your body text here. You can write multiple paragraphs.</p>' },
    graphic:         { type:'graphic', _graphic: PH_GFX, displayTitle:'Image', body:'' },
    'graphic-text':  { type:'graphic-text', displayTitle:'Your Heading Here', body:'<p>Describe the key concept shown in this image. Add context, explanation, or a supporting narrative that complements the visual.</p>', _graphic: PH_GFX },
    accordion:       { type:'accordion', displayTitle:'Your Heading Here', items:[{title:'Panel 1',body:'Content for this panel.'},{title:'Panel 2',body:'Content for this panel.'}] },
    mcq:             { type:'mcq', displayTitle:'Your Question Here', body:'<p>Select the best answer.</p>', choices:[{id:'a',text:'Option A',isCorrect:true},{id:'b',text:'Option B'},{id:'c',text:'Option C'}], _feedback:{correct:'Correct!',incorrect:'Try again.'} },
    narrative:       { type:'narrative', displayTitle:'Your Heading Here', items:[{title:'Slide 1',body:'Content for slide 1.',_graphic:PH_GFX},{title:'Slide 2',body:'Content for slide 2.',_graphic:PH_GFX}] },
    bento:           { type:'bento', displayTitle:'Your Heading Here', body:'<p>Overview text.</p>', items:[{title:'Card 1',body:'Card content.',_graphic:PH_GFX},{title:'Card 2',body:'Card content.',_graphic:PH_GFX},{title:'Card 3',body:'Card content.'},{title:'Card 4',body:'Card content.'}] },
    'data-table':    { type:'data-table', displayTitle:'Your Heading Here', body:'<p>Table description.</p>', columns:[{title:'Column A'},{title:'Column B'}], rows:[{label:'Row 1',values:['Value A','Value B']},{label:'Row 2',values:['Value A','Value B']}] },
    media:           { type:'media', displayTitle:'Your Heading Here', body:'<p>Video description.</p>', _media:{src:'',poster:PH_IMG} },
    textinput:       { type:'textinput', displayTitle:'Your Question Here', body:'<p>Enter your response below.</p>', instruction:'Type your answer', placeholder:'Your answer here...' },
    branching:       { type:'branching', displayTitle:'Your Scenario Here', body:'<p>Choose the best approach.</p>', choices:[{id:'a',text:'Option A',body:'What happens if you choose A.'},{id:'b',text:'Option B',body:'What happens if you choose B.'}] },
    timeline:        { type:'timeline', displayTitle:'Your Heading Here', body:'<p>Follow these steps.</p>', items:[{title:'Step 1',body:'First step details.'},{title:'Step 2',body:'Second step details.'},{title:'Step 3',body:'Third step details.'}] },
    comparison:      { type:'comparison', displayTitle:'Your Heading Here', body:'<p>Compare the options.</p>', columns:[{title:'Option A',items:[{text:'Feature 1',value:true},{text:'Feature 2',value:false}]},{title:'Option B',items:[{text:'Feature 1',value:false},{text:'Feature 2',value:true}]}] },
    'stat-callout':  { type:'stat-callout', displayTitle:'Key Statistics', stats:[{value:'100',suffix:'%',label:'Stat One'},{value:'50',suffix:'K',label:'Stat Two'},{value:'3.5',suffix:'x',label:'Stat Three'}] },
    pullquote:       { type:'pullquote', body:'Enter your quote text here.', attribution:'Attribution', role:'Role' },
    'key-term':      { type:'key-term', displayTitle:'Key Terms', items:[{term:'Term 1',definition:'Definition of term 1.'},{term:'Term 2',definition:'Definition of term 2.'}] },
    checklist:       { type:'checklist', displayTitle:'Your Checklist', body:'<p>Complete these items.</p>', instruction:'Check each item as you complete it.', items:[{text:'Item 1'},{text:'Item 2'},{text:'Item 3'}] },
    tabs:            { type:'tabs', displayTitle:'Your Heading Here', tabs:[{label:'Tab 1',body:'Content for tab 1.'},{label:'Tab 2',body:'Content for tab 2.'},{label:'Tab 3',body:'Content for tab 3.'}] },
    flashcard:       { type:'flashcard', displayTitle:'Your Heading Here', cards:[{front:'Front of card 1',back:'Back of card 1'},{front:'Front of card 2',back:'Back of card 2'},{front:'Front of card 3',back:'Back of card 3'}] },
    'labeled-image': { type:'labeled-image', displayTitle:'Your Heading Here', instruction:'Click the markers.', _graphic:PH_GFX, _markers:[{x:25,y:30,label:'Marker 1',description:'Description 1.'},{x:75,y:60,label:'Marker 2',description:'Description 2.'}] },
    'process-flow':  { type:'process-flow', displayTitle:'Your Heading Here', body:'<p>Process overview.</p>', nodes:[{title:'Step 1',body:'First step.'},{title:'Step 2',body:'Second step.'},{title:'Step 3',body:'Third step.'}] },
    'image-gallery': { type:'image-gallery', displayTitle:'Your Heading Here', body:'<p>Gallery description.</p>', items:[{_graphic:PH_GFX,caption:'Caption 1'},{_graphic:PH_GFX,caption:'Caption 2'}] },
    'full-bleed':    { type:'full-bleed', displayTitle:'Your Heading Here', body:'<p>Overlay text on this full-width image.</p>', _graphic:PH_GFX },
    'video-transcript':{ type:'video-transcript', displayTitle:'Your Heading Here', body:'<p>Video description.</p>', _media:{src:'',poster:PH_IMG}, transcript:'Transcript text goes here.' },
    divider:         { type:'divider', style:'line' },
    callout:         { type:'callout', displayTitle:'Callout Title', body:'<p>Callout content here.</p>', calloutType:'info' },
    'path-selector': { type:'path-selector', displayTitle:'Choose Your Path', instruction:'Select a learning path.', items:[{id:'path-a',title:'Path A',body:'Description of path A.'},{id:'path-b',title:'Path B',body:'Description of path B.'}], pathGroup:'default' },
  };

  // Variant map for template library (matches src/utils.ts VARIANT_MAP)
  const TPL_VARIANTS = {
    'hero':['centered-overlay','split-screen','minimal-text'],'graphic-text':['split','overlap','full-overlay'],
    'bento':['grid-4','wide-2','featured'],'accordion':['standard','accent-border'],'mcq':['stacked','grid'],
    'stat-callout':['centered','card-row'],'timeline':['vertical','centered-alternating'],
    'comparison':['columns','stacked-rows'],'tabs':['horizontal','vertical'],
    'pullquote':['accent-bar','centered','minimal'],'full-bleed':['center','left','right'],
    'process-flow':['vertical','horizontal'],'graphic':['standard','captioned-card'],
    'divider':['line','spacing','icon'],'callout':['info','warning','tip','success'],
    'text':['standard','two-column','highlight-box'],'narrative':['image-focused','text-focused'],
    'flashcard':['grid','single-large'],'checklist':['standard','card-style','numbered'],
    'key-term':['list','card-grid'],'labeled-image':['numbered-dots','side-panel'],
    'data-table':['standard','striped-card'],'branching':['cards','list'],
  };

  const templateLibraryHtml = Object.entries(PLACEHOLDER_DATA).map(([type, placeholder]) => {
    const comp = { ...placeholder, componentId: `tpl-${type}` };
    // Render default variant
    let html = renderComponentVariant(comp, 0, 'standard');
    if (!html) return '';

    // Add data-variant to default
    const variants = TPL_VARIANTS[type];
    if (variants && variants.length > 1) {
      const defaultVariant = variants[0];
      html = html.replace(/^(<section\b[^>]*)>/, `$1 data-variant="${defaultVariant}">`);

      // Render alternate variants as <template data-variant-alt> tags
      const alts = [];
      for (const v of variants.slice(1)) {
        const altHtml = renderComponentVariant(comp, 0, 'standard', v);
        if (altHtml) {
          const tagged = altHtml.replace(/^(<section\b[^>]*)>/, `$1 data-variant="${v}">`);
          alts.push(`<template data-variant-alt="${esc(v)}">${tagged}</template>`);
        }
      }
      if (alts.length > 0) {
        html = html.replace(/<\/section>\s*$/, `${alts.join('\n')}\n</section>`);
      }
    }

    return `<template data-type-template="${type}">${html}</template>`;
  }).filter(Boolean).join('\n');

  console.log(`[ok] Template library: ${Object.keys(PLACEHOLDER_DATA).length} component types\n`);

  // Get hydration script
  let hydrateScript = '';
  if (fs.existsSync(HYDRATE_PATH)) {
    hydrateScript = fs.readFileSync(HYDRATE_PATH, 'utf-8');
  }

  // Theme + course title
  const isDark = tokens.isDark !== false;
  const courseTitle = layout.course.title || 'Course';

  // ── Build CSS ──────────────────────────────────────────────────────
  const useTailwindV4 = !process.argv.includes('--tw-cdn');
  let finalHead;

  if (useTailwindV4 && fs.existsSync(THEME_TEMPLATE)) {
    // Tailwind v4: write body HTML for class scanning, then compile CSS
    const bodyHtml = `${navHtml}\n${sectionsHtmlStr}\n${templateLibraryHtml}`;
    const scanPath = path.resolve(ROOT, 'engine/output/_tw-scan.html');
    fs.writeFileSync(scanPath, bodyHtml, 'utf-8');

    const compiledCSS = buildTailwindCSS(tokens);
    finalHead = generateHeadV4(tokens, courseTitle, compiledCSS);

    // Clean up scan file
    fs.unlinkSync(scanPath);
  } else {
    // CDN fallback (--tw-cdn flag or no template)
    finalHead = generateHead(tokens, courseTitle);
  }
  console.log(`[ok] Generated <head> (${finalHead.length} chars, ${useTailwindV4 ? 'Tailwind v4' : 'CDN JIT'})`);

  let finalHtml = `<!DOCTYPE html>
<html class="${isDark ? 'dark' : ''}" lang="en">
<head>
${finalHead}
</head>
<body class="bg-background text-on-background font-body selection:bg-primary-container selection:text-on-primary-container">

${navHtml}

<main class="min-h-screen bg-background overflow-x-hidden pt-14">
${sectionsHtmlStr}

<!-- Template Library (authoring layer — hidden) -->
<div id="component-templates" style="display:none">
${templateLibraryHtml}
</div>

<!-- Course Completion -->
<section class="py-16 text-center">
<div class="max-w-xl mx-auto px-8">
  <div class="w-16 h-16 mx-auto mb-6 rounded-full bg-secondary/10 flex items-center justify-center">
    <span class="material-symbols-outlined text-3xl text-secondary">verified_user</span>
  </div>
  <h2 class="font-headline text-h3 mb-3">Course Complete</h2>
  <p class="text-body text-on-surface-variant mb-8">
    You have completed ${esc(courseTitle)}. Review any sections as needed.
  </p>
  <button class="btn-primary px-8 py-3 rounded-full font-bold text-sm" onclick="window.scrollTo({top:0,behavior:'smooth'})">Return to Top</button>
</div>
</section>
</main>

<script type="application/json" id="course-data">${JSON.stringify(layout).replace(/<\//g, '<\\/')}</script>
<script type="application/json" id="surface-rhythm">${JSON.stringify({
  rhythm: AR.surfaceRhythm || [],
  accentSectionBg: colorStrategy?.accentSectionBg ?? true,
}).replace(/<\//g, '<\\/')}</script>
<script type="application/json" id="category-meta">${JSON.stringify({
  map: CATEGORY_MAP,
  colors: {
    Text: '#3b82f6', Image: '#8b5cf6', Explore: '#10b981',
    Quiz: '#ef4444', Layout: '#f59e0b', Media: '#06b6d4', Structure: '#ec4899'
  },
  labels: {
    Text: 'Text', Image: 'Image', Explore: 'Explore',
    Quiz: 'Quiz', Layout: 'Layout', Media: 'Media', Structure: 'Structure'
  }
}).replace(/<\//g, '<\\/')}</script>
<script>
${hydrateScript}
</script>
</body>
</html>`;

  // Strip empty heading tags (defensive: AI content may omit displayTitle)
  finalHtml = finalHtml.replace(/<h([1-6])([^>]*)>\s*<\/h\1>/g, '');

  // Write outputs
  fs.mkdirSync(path.dirname(OUTPUT_PATH), { recursive: true });
  fs.writeFileSync(OUTPUT_PATH, finalHtml, 'utf-8');
  console.log(`[ok] Written: ${OUTPUT_PATH} (${(finalHtml.length / 1024).toFixed(0)} KB)`);

  fs.writeFileSync(PAGES_PATH, finalHtml, 'utf-8');
  console.log(`[ok] Written: ${PAGES_PATH}`);

  console.log('\nBuild complete!');
}

build();
